#!/usr/bin/env bash
set -euo pipefail
umask 077
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"
ALLOWED_DB_NAME="airtrust-db-staging-baseline-20260701"; target=""
for arg in "$@"; do case "$arg" in --target=*) target="${arg#*=}" ;; *) echo "ERROR: unknown argument: $arg" >&2; exit 1 ;; esac; done
[[ "$target" == "$ALLOWED_DB_NAME" ]] || { echo "ERROR: staging 0526 postconditions refused target: $target" >&2; exit 1; }
query_count(){ local sql="$1"; (cd worker-airtrust && npx wrangler d1 execute "$target" --remote --json --command "$sql") | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{const p=JSON.parse(d);const r=p[0]?.results?.[0]||{};console.log(Number(r.count??r.total??Object.values(r)[0]??0))})"; }
assert_count(){ local label="$1" expected="$2" sql="$3" count; count="$(query_count "$sql")"; [[ "$count" == "$expected" ]] || { echo "ERROR: $label expected=$expected found=$count" >&2; exit 1; }; echo "POSTCONDITION_OK=$label"; }
MNT_NAMES="'Mecânico','Mecanico','MECÂNICO','MECANICO','Aux Manutenção','Aux Manutencao','Auxiliar de Manutenção','Auxiliar de Manutencao'"
NR20_NAMES="$MNT_NAMES,'Aux Suprimentos','Auxiliar de Suprimentos','Supervisor Suprimentos','Supervisor de Suprimentos'"
assert_count migration-ledger-0526 1 "SELECT COUNT(*) count FROM d1_migrations WHERE name='0526_training_compliance_matrix_alignment.sql';"
assert_count sgso-cycle 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND UPPER(codigo)='D2' AND validade=36 AND carga_horaria_inicial=8 AND carga_horaria_recorrente=4 AND deleted_at IS NULL;"
assert_count pre-cycle 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND UPPER(codigo)='PRE' AND validade=12 AND deleted_at IS NULL;"
assert_count loft-active 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND UPPER(codigo)='LOFT' AND ativo=1 AND deleted_at IS NULL;"
assert_count loft-flightcrew-missing 0 "SELECT COUNT(*) count FROM funcoes f WHERE f.empresa_id=6 AND f.ativo=1 AND f.deleted_at IS NULL AND f.nome IN ('Comandante','Copiloto') AND NOT EXISTS (SELECT 1 FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo='LOFT' AND tr.escopo='FUNCAO' AND tr.funcao_id=f.id AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL);"
assert_count aw139-validity 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND codigo='MNT_AW139' AND validade=24 AND deleted_at IS NULL;"
assert_count s76-validity 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND codigo='MNT_S76AC' AND validade=24 AND deleted_at IS NULL;"
assert_count maintenance-provenance-missing 0 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo IN ('MNT_AW139','MNT_S76AC') AND tr.obrigatoriedade<>'NAO_APLICA' AND tr.ativo=1 AND tr.deleted_at IS NULL AND (tr.origem<>'CLIENTE' OR tr.fundamento_tipo<>'CONTRATUAL_CLIENTE');"
assert_count nr11-missing 0 "SELECT COUNT(*) count FROM funcoes f WHERE f.empresa_id=6 AND f.ativo=1 AND f.deleted_at IS NULL AND f.nome IN ($MNT_NAMES) AND NOT EXISTS (SELECT 1 FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo='NR-11' AND tr.escopo='FUNCAO' AND tr.funcao_id=f.id AND tr.ativo=1 AND tr.deleted_at IS NULL);"
assert_count nr20-model 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND codigo='NR-20' AND validade=24 AND carga_horaria_inicial=16 AND carga_horaria_recorrente=4 AND deleted_at IS NULL;"
assert_count nr20-missing 0 "SELECT COUNT(*) count FROM funcoes f WHERE f.empresa_id=6 AND f.ativo=1 AND f.deleted_at IS NULL AND f.nome IN ($NR20_NAMES) AND NOT EXISTS (SELECT 1 FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo='NR-20' AND tr.escopo='FUNCAO' AND tr.funcao_id=f.id AND tr.modalidade_requerida='HIBRIDO' AND tr.ativo=1 AND tr.deleted_at IS NULL);"
assert_count nr35-model 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND codigo='NR-35' AND validade=24 AND carga_horaria_inicial=8 AND categoria='Presencial' AND deleted_at IS NULL;"
assert_count nr35-missing 0 "SELECT COUNT(*) count FROM funcoes f WHERE f.empresa_id=6 AND f.ativo=1 AND f.deleted_at IS NULL AND f.nome IN ($MNT_NAMES) AND NOT EXISTS (SELECT 1 FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo='NR-35' AND tr.escopo='FUNCAO' AND tr.funcao_id=f.id AND tr.modalidade_requerida='PRESENCIAL' AND tr.ativo=1 AND tr.deleted_at IS NULL);"
assert_count nr26-rampa 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id JOIN funcoes f ON f.id=tr.funcao_id WHERE tr.empresa_id=6 AND qt.codigo='NR-26' AND f.nome IN ('Agente Rampa','Agente de Rampa') AND tr.escopo='FUNCAO' AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count nr26-mechanic 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id JOIN funcoes f ON f.id=tr.funcao_id WHERE tr.empresa_id=6 AND qt.codigo='NR-26' AND f.nome IN ('Mecânico','Mecanico','MECÂNICO','MECANICO') AND tr.escopo='FUNCAO' AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count avsec-company-rule 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo='AVSEC_CONSC' AND tr.escopo='EMPRESA' AND tr.obrigatoriedade='OBRIGATORIA' AND tr.condicao_id IS NULL AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count specific-condition-catalog 5 "SELECT COUNT(*) count FROM compliance_condicoes WHERE empresa_id=6 AND codigo IN ('FDM_ADMIN','FDM_COMITE','LOSA_ANALISTA','EDB_LOGBOOK_USUARIO','GESTAO_MUDANCAS_PARTICIPANTE') AND ativo=1 AND deleted_at IS NULL;"
assert_count inferred-new-assignments 0 "SELECT COUNT(*) count FROM funcionarios_compliance_condicoes fcc JOIN compliance_condicoes cc ON cc.id=fcc.condicao_id AND cc.empresa_id=fcc.empresa_id WHERE fcc.empresa_id=6 AND cc.codigo IN ('FDM_ADMIN','FDM_COMITE','LOSA_ANALISTA','EDB_LOGBOOK_USUARIO','GESTAO_MUDANCAS_PARTICIPANTE') AND fcc.ativo=1 AND fcc.deleted_at IS NULL;"
echo TRAINING_COMPLIANCE_MATRIX_ALIGNMENT_0526_STAGING_POSTCONDITIONS=PASS
