#!/usr/bin/env bash
set -euo pipefail
umask 077
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"
ALLOWED_DB_NAME="airtrust-db"; target="$ALLOWED_DB_NAME"
for arg in "$@"; do case "$arg" in --target=*) target="${arg#*=}" ;; *) echo "ERROR: unknown argument: $arg" >&2; exit 1 ;; esac; done
[[ "$target" == "$ALLOWED_DB_NAME" ]] || { echo "ERROR: 0535 postcondition refused target" >&2; exit 1; }
query_count(){ local sql="$1"; (cd worker-airtrust && npx wrangler d1 execute "$target" --env production --remote --json --command "$sql") | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{const p=JSON.parse(d);const r=p[0]?.results?.[0]||{};console.log(Number(r.count??r.total??Object.values(r)[0]??0))})"; }
assert_count(){ local label="$1" expected="$2" sql="$3" count; count="$(query_count "$sql")"; [[ "$count" == "$expected" ]] || { echo "ERROR: $label expected=$expected found=$count" >&2; exit 1; }; echo "POSTCONDITION_OK=$label"; }
assert_equal_counts(){ local label="$1" expected_sql="$2" actual_sql="$3" expected actual; expected="$(query_count "$expected_sql")"; actual="$(query_count "$actual_sql")"; [[ "$expected" == "$actual" ]] || { echo "ERROR: $label expected=$expected found=$actual" >&2; exit 1; }; echo "POSTCONDITION_OK=$label"; }
assert_count schema-v2-0535 1 "SELECT COUNT(*) count FROM airtrust_schema_changes_v2 WHERE change_id=\'training-compliance-fdm-three-audiences-0535\' AND baseline_id=\'production-d1-baseline-v2-20260714\';"
assert_count two-new-models 2 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND codigo IN ('FDM-TRIPULACAO','FDM-COMITE-GATEKEEPER') AND ativo=1 AND deleted_at IS NULL;"
assert_count canonically-categorized-unspecified-models 2 "SELECT COUNT(*) count FROM qualificacoes_tipos qt JOIN qualificacoes_categorias qc ON qc.id=qt.categoria_id AND qc.empresa_id=qt.empresa_id WHERE qt.empresa_id=6 AND qt.codigo IN ('FDM-TRIPULACAO','FDM-COMITE-GATEKEEPER') AND qt.ativo=1 AND qt.deleted_at IS NULL AND qc.codigo='TREINAMENTO_OPERACIONAL' AND qc.ativo=1 AND qc.deleted_at IS NULL AND qt.validade IS NULL AND qt.carga_horaria IS NULL;"
assert_count existing-fdm-mnt-unmodified-metadata 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND codigo='FDM-MECANICO' AND nome='Treinamento de FDM - MNT' AND categoria='EAD' AND validade IS NULL AND carga_horaria=1 AND ativo=1 AND deleted_at IS NULL;"
assert_count two-formal-condition-rules 2 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id JOIN compliance_condicoes cc ON cc.id=tr.condicao_id AND cc.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND qt.codigo='FDM-COMITE-GATEKEEPER' AND cc.codigo IN ('FDM_COMITE','GATEKEEPER') AND cc.tipo='DESIGNACAO' AND tr.escopo='EMPRESA' AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_equal_counts pilot-function-rules "SELECT COUNT(*) count FROM funcoes WHERE empresa_id=6 AND ativo=1 AND deleted_at IS NULL AND UPPER(TRIM(nome)) IN ('COMANDANTE','COPILOTO');" "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id JOIN funcoes f ON f.id=tr.funcao_id AND f.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND qt.codigo='FDM-TRIPULACAO' AND tr.escopo='FUNCAO' AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL AND f.ativo=1 AND f.deleted_at IS NULL AND UPPER(TRIM(f.nome)) IN ('COMANDANTE','COPILOTO');"
assert_equal_counts comite-function-rules "SELECT COUNT(*) count FROM funcoes WHERE empresa_id=6 AND ativo=1 AND deleted_at IS NULL AND UPPER(TRIM(nome)) IN ('GERENTE DE SEGURANÇA OPERACIONAL','GERENTE DE SEGURANCA OPERACIONAL','GERENTE DE MANUTENÇÃO','GERENTE DE MANUTENCAO','GERENTE DE OPERAÇÕES','GERENTE DE OPERACOES','ANALISTA DE FDM','ANALISTA FDM','COORDENADOR DE FDM','COORDENADOR FDM','COORDENADOR DE ENGENHARIA');" "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id JOIN funcoes f ON f.id=tr.funcao_id AND f.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND qt.codigo='FDM-COMITE-GATEKEEPER' AND tr.escopo='FUNCAO' AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL AND f.ativo=1 AND f.deleted_at IS NULL AND UPPER(TRIM(f.nome)) IN ('GERENTE DE SEGURANÇA OPERACIONAL','GERENTE DE SEGURANCA OPERACIONAL','GERENTE DE MANUTENÇÃO','GERENTE DE MANUTENCAO','GERENTE DE OPERAÇÕES','GERENTE DE OPERACOES','ANALISTA DE FDM','ANALISTA FDM','COORDENADOR DE FDM','COORDENADOR FDM','COORDENADOR DE ENGENHARIA');"
assert_count no-improvised-lms-course 0 "SELECT COUNT(*) count FROM lms_cursos c JOIN qualificacoes_tipos qt ON qt.id=c.qualificacao_tipo_id AND qt.empresa_id=c.empresa_id WHERE c.empresa_id=6 AND qt.codigo IN ('FDM-TRIPULACAO','FDM-COMITE-GATEKEEPER') AND c.deleted_at IS NULL;"
echo TRAINING_COMPLIANCE_FDM_THREE_AUDIENCES_0535_PRODUCTION_POSTCONDITIONS=PASS
