#!/usr/bin/env bash
# Read-only production postconditions for Schema V2 change 0498.
set -euo pipefail
umask 077
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"
ALLOWED_DB_NAME="airtrust-db"; BASELINE_ID="production-d1-baseline-v2-20260714"; CHANGE_ID="frms-parametric-v2-0498"
target="$ALLOWED_DB_NAME"
for arg in "$@"; do case "$arg" in --target=*) target="${arg#*=}" ;; *) echo "ERROR: unknown argument: $arg" >&2; exit 1 ;; esac; done
[[ "$target" == "$ALLOWED_DB_NAME" ]] || { echo "ERROR: 0498 production postconditions refused target: $target" >&2; exit 1; }
query_count(){ local sql="$1"; node - "$target" "$sql" <<'NODE'
const {spawnSync}=require('node:child_process'),path=require('node:path');const[,,db,sql]=process.argv;const r=spawnSync('npx',['wrangler','d1','execute',db,'--env','production','--remote','--json','--command',sql],{cwd:path.join(process.cwd(),'worker-airtrust'),encoding:'utf8',env:process.env});if(r.status!==0){process.stderr.write(r.stderr||r.stdout);process.exit(1)}let p;try{p=JSON.parse(r.stdout)}catch{const s=r.stdout.indexOf('['),e=r.stdout.lastIndexOf(']');if(s<0||e<=s)throw new Error('D1_JSON_NOT_FOUND');p=JSON.parse(r.stdout.slice(s,e+1))}const row=(Array.isArray(p)?p[0]?.results:p?.results)?.[0],n=Number(row?.count??row?.total??row?.['COUNT(*)']??(row?Object.values(row)[0]:NaN));if(!Number.isInteger(n)||n<0)throw new Error('INVALID_COUNT');process.stdout.write(String(n));
NODE
}
assert_count(){ local label="$1" expected="$2" sql="$3" count; count="$(query_count "$sql")"; [[ "$count" == "$expected" ]] || { echo "ERROR: $label expected=$expected found=$count" >&2; exit 1; }; echo "POSTCONDITION_OK=$label"; }
assert_positive(){ local label="$1" sql="$2" count; count="$(query_count "$sql")"; [[ "$count" -ge 1 ]] || { echo "ERROR: $label expected>=1 found=$count" >&2; exit 1; }; echo "POSTCONDITION_OK=$label:$count"; }
assert_count active-baseline 1 "SELECT COUNT(*) count FROM airtrust_schema_baselines_v2 WHERE baseline_id='$BASELINE_ID' AND status='ACTIVE';"
assert_count schema-v2-change 1 "SELECT COUNT(*) count FROM airtrust_schema_changes_v2 WHERE change_id='$CHANGE_ID';"
assert_count recovery-tables 3 "SELECT COUNT(*) count FROM sqlite_master WHERE type='table' AND name IN ('frms_recovery_activity_day','frms_recovery_activity_segment','frms_recovery_assessment');"
assert_count rolling-v2-columns 2 "SELECT COUNT(*) count FROM pragma_table_info('frms_acumulo_rolling') WHERE name IN ('hv_ano_calendario_min','pct_limite_ano_calendario');"
assert_count recovery-v2-columns 8 "SELECT COUNT(*) count FROM pragma_table_info('frms_recovery_assessment') WHERE name IN ('absolute_rest_hours','no_work_hours','recovery_credit_points','recovery_credit_base_points','recovery_rest_factor','recovery_callout_multiplier','config_revision_id','policy_version');"
assert_count factorization-v2-columns 9 "SELECT COUNT(*) count FROM pragma_table_info('frms_fatorizacao_jornada') WHERE name IN ('operational_load_imc_delta','operational_load_imc_quality','operational_load_imc_json','recovery_credit_requested_points','recovery_credit_applied_points','hv_v2_raw_penalty_points','hv_v2_credit_applied_points','hv_v2_delta_points','hv_v2_credit_generated_points');"
assert_count recovery-credit-index 1 "SELECT COUNT(*) count FROM sqlite_master WHERE type='index' AND name='idx_frms_recovery_credit_day';"
assert_positive active-v2-revisions "SELECT COUNT(*) count FROM frms_config_revisions WHERE status='ACTIVE' AND profile_code='HELICOPTER_OFFSHORE' AND policy_version='FRMS_OPERATIONAL_POLICY_V2' AND id LIKE '%-v2-0498';"
assert_count no-active-legacy-offshore-revision 0 "SELECT COUNT(*) count FROM frms_config_revisions WHERE status='ACTIVE' AND profile_code='HELICOPTER_OFFSHORE' AND effective_from <= '2026-09-17' AND (effective_to IS NULL OR effective_to >= '2026-09-17') AND policy_version <> 'FRMS_OPERATIONAL_POLICY_V2';"
assert_count v2-critical-parameter-drift 0 "SELECT COUNT(*) count FROM frms_config_revisions r WHERE r.policy_version='FRMS_OPERATIONAL_POLICY_V2' AND r.id LIKE '%-v2-0498' AND (NOT EXISTS (SELECT 1 FROM frms_config_parameters p WHERE p.revision_id=r.id AND p.parameter_key='FRMS_V2_ENABLED' AND p.numeric_value=1) OR NOT EXISTS (SELECT 1 FROM frms_config_parameters p WHERE p.revision_id=r.id AND p.parameter_key='LANDINGS_NEUTRAL_MAX' AND p.numeric_value=8) OR NOT EXISTS (SELECT 1 FROM frms_config_parameters p WHERE p.revision_id=r.id AND p.parameter_key='PRESENTATION_NIGHT_START_HOUR' AND p.numeric_value=22) OR NOT EXISTS (SELECT 1 FROM frms_config_parameters p WHERE p.revision_id=r.id AND p.parameter_key='WOCL_START_MINUTE' AND p.numeric_value=120) OR NOT EXISTS (SELECT 1 FROM frms_config_parameters p WHERE p.revision_id=r.id AND p.parameter_key='WOCL_END_MINUTE' AND p.numeric_value=360) OR NOT EXISTS (SELECT 1 FROM frms_config_parameters p WHERE p.revision_id=r.id AND p.parameter_key='WOCL_CENTER_PENALTY' AND ABS(p.numeric_value-0.015)<0.000001));"
assert_count v2-legacy-double-count-drift 0 "SELECT COUNT(*) count FROM frms_config_parameters p JOIN frms_config_revisions r ON r.id=p.revision_id WHERE r.policy_version='FRMS_OPERATIONAL_POLICY_V2' AND r.id LIKE '%-v2-0498' AND p.parameter_key IN ('APRESENTACAO_TARDE_FATOR','HV_POUCAS_FATOR','HV_NORMAL_FATOR','HV_MUITAS_FATOR','NOTURNO_FATOR','FORTNIGHT_IMPACT_DAYS_WITHOUT_DUTY') AND COALESCE(p.numeric_value,0) <> 0;"
echo FRMS_PARAMETRIC_V2_0498_PRODUCTION_POSTCONDITIONS=PASS
