#!/usr/bin/env bash
set -euo pipefail
umask 077
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
target=airtrust-db
for arg in "$@"; do case "$arg" in --target=*) target="${arg#*=}" ;; *) echo "UNSUPPORTED_ARG" >&2; exit 1 ;; esac; done
[[ "$target" == airtrust-db ]] || { echo "WRONG_D1_TARGET" >&2; exit 1; }
query_count(){ local sql="$1"; (cd worker-airtrust && npx wrangler d1 execute "$target" --env production --remote --json --command "$sql") | node -e "let s='';process.stdin.on('data',x=>s+=x);process.stdin.on('end',()=>{let a=JSON.parse(s);let n=Number(a[0]?.results?.[0]?.count);if(!Number.isSafeInteger(n)||n<0)process.exit(1);console.log(n)})"; }
assert_count(){ local name="$1" expected="$2" sql="$3" n; n="$(query_count "$sql")"; [[ "$n" == "$expected" ]] || { echo "0548_CHECK_FAILED:$name expected=$expected actual=$n" >&2; exit 1; }; echo "PASS:$name"; }
assert_count applied-0548 1 "SELECT COUNT(*) count FROM airtrust_schema_changes_v2 WHERE change_id='training-compliance-maintenance-iio-aprs-assistants-0548' AND baseline_id='production-d1-baseline-v2-20260714'"
assert_count total-active-rules 3 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND qt.codigo='MNT_IIO_APRS' AND tr.ativo=1 AND tr.deleted_at IS NULL"
assert_count active-assistant-rule 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id JOIN funcoes f ON f.id=tr.funcao_id AND f.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND qt.codigo='MNT_IIO_APRS' AND tr.escopo='FUNCAO' AND f.nome='Auxiliar de Manutenção' AND tr.obrigatoriedade='OBRIGATORIA' AND tr.auto_matricular_ead=0 AND tr.ativo=1 AND tr.deleted_at IS NULL"
assert_count existing-mechanic 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id JOIN funcoes f ON f.id=tr.funcao_id AND f.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND qt.codigo='MNT_IIO_APRS' AND f.nome='Mecânico' AND tr.ativo=1 AND tr.deleted_at IS NULL"
assert_count existing-engineering-coordinator 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id JOIN funcoes f ON f.id=tr.funcao_id AND f.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND qt.codigo='MNT_IIO_APRS' AND f.nome='Coordenador de Engenharia' AND tr.ativo=1 AND tr.deleted_at IS NULL"
assert_count assistant-fields-match-source 0 "SELECT COUNT(*) count FROM treinamento_requisitos a JOIN treinamento_requisitos m ON a.empresa_id=m.empresa_id AND a.qualificacao_tipo_id=m.qualificacao_tipo_id JOIN funcoes fa ON fa.id=a.funcao_id AND fa.empresa_id=a.empresa_id JOIN funcoes fm ON fm.id=m.funcao_id AND fm.empresa_id=m.empresa_id JOIN qualificacoes_tipos qt ON qt.id=a.qualificacao_tipo_id AND qt.empresa_id=a.empresa_id WHERE a.empresa_id=6 AND qt.codigo='MNT_IIO_APRS' AND fa.nome='Auxiliar de Manutenção' AND fm.nome='Mecânico' AND a.ativo=1 AND m.ativo=1 AND (COALESCE(a.modalidade_requerida,'')<>COALESCE(m.modalidade_requerida,'') OR COALESCE(a.validade_fonte,'')<>COALESCE(m.validade_fonte,'') OR a.auto_matricular_ead<>m.auto_matricular_ead)"
echo 'TRAINING_COMPLIANCE_0548_POSTCONDITIONS=PASS'
