#!/usr/bin/env bash
set -euo pipefail
umask 077
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"
ALLOWED_DB_NAME="airtrust-db"; BASELINE_ID="production-d1-baseline-v2-20260714"; CHANGE_ID="training-catalog-metadata-references-0533"; target="$ALLOWED_DB_NAME"
for arg in "$@"; do case "$arg" in --target=*) target="${arg#*=}" ;; *) echo "ERROR: unknown argument: $arg" >&2; exit 1 ;; esac; done
[[ "$target" == "$ALLOWED_DB_NAME" ]] || { echo "ERROR: 0533 production postconditions refused target: $target" >&2; exit 1; }
query_count(){ local sql="$1"; (cd worker-airtrust && npx wrangler d1 execute "$target" --env production --remote --json --command "$sql") | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{const p=JSON.parse(d);const r=p[0]?.results?.[0]||{};console.log(Number(r.count??r.total??Object.values(r)[0]??0))})"; }
assert_count(){ local label="$1" expected="$2" sql="$3" count; count="$(query_count "$sql")"; [[ "$count" == "$expected" ]] || { echo "ERROR: $label expected=$expected found=$count" >&2; exit 1; }; echo "POSTCONDITION_OK=$label"; }
assert_count schema-v2-change 1 "SELECT COUNT(*) count FROM airtrust_schema_changes_v2 WHERE change_id='$CHANGE_ID' AND baseline_id='$BASELINE_ID';"
assert_count qualificacoes-referencias-present 1 "SELECT COUNT(*) count FROM pragma_table_info('qualificacoes_tipos') WHERE name='referencias';"
assert_count lms-referencias-present 1 "SELECT COUNT(*) count FROM pragma_table_info('lms_cursos') WHERE name='referencias';"
assert_count reviewed-lms-metadata-missing 0 "SELECT COUNT(*) count FROM lms_cursos c JOIN qualificacoes_tipos qt ON qt.id=c.qualificacao_tipo_id AND qt.empresa_id=c.empresa_id WHERE c.empresa_id=6 AND c.ativo=1 AND c.deleted_at IS NULL AND UPPER(TRIM(qt.codigo)) IN ('A','AUD_COMP','B','C','COD_ETICA','CRM_DIR_RBAC119','D2','E1','E2','E4','E5','E6','FDM-EAD','FOD','GATEKEEPER','HELIWISE','I','INTEGRA','INTRO_SGQ','JUST_CULTURE','LGPD','LOSA','MNT_AW139','MNT_HUMS','MNT_IIO_APRS','MNT_INTEGRACAO_DOUTRINACAO','MNT_MCQ','MNT_MEL','MNT_MGM','MNT_MOM','MUDA','N','NR-05','NR-11','NR-20','NR-26','NR-35','NR06','P','PETRO-OURO','PPSP','PPSP_SUP','PRE','PT6C-67C','REG-ANAC','SOP_AW139','SOP_S76','STOP_WORK','COL_SEL') AND (COALESCE(TRIM(c.descricao),'')='' OR COALESCE(TRIM(c.conteudo_programatico),'')='' OR COALESCE(TRIM(c.referencias),'')='');"
assert_count probe-marker-removed 0 "SELECT COUNT(*) count FROM lms_cursos WHERE empresa_id=6 AND COALESCE(observacoes,'') LIKE 'ssot-probe-curl-%';"
assert_count maintenance-36-models 0 "SELECT COUNT(*) count FROM qualificacoes_tipos qt JOIN qualificacoes_areas qa ON qa.id=qt.area_id AND qa.empresa_id=qt.empresa_id WHERE qt.empresa_id=6 AND qt.ativo=1 AND qt.deleted_at IS NULL AND qa.nome='Manutenção' AND qt.validade=36;"
assert_count maintenance-targets-not-24 0 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND UPPER(TRIM(codigo)) IN ('MNT_ARRIEL2','MNT_ARRIEL2_DESM_MOD','MNT_HUMS','MNT_IRM','MNT_IIO_APRS','MNT_MCQ','MNT_MGM','MNT_MOM') AND (validade<>24 OR validade IS NULL) AND ativo=1 AND deleted_at IS NULL;"
assert_count maintenance-history-not-24 0 "SELECT COUNT(*) count FROM qualificacoes_historico qh WHERE qh.empresa_id=6 AND qh.deleted_at IS NULL AND EXISTS (SELECT 1 FROM qualificacoes_tipos qt WHERE qt.empresa_id=6 AND UPPER(TRIM(qt.codigo)) IN ('MNT_ARRIEL2','MNT_ARRIEL2_DESM_MOD','MNT_HUMS','MNT_IRM','MNT_IIO_APRS','MNT_MCQ','MNT_MGM','MNT_MOM') AND qt.ativo=1 AND qt.deleted_at IS NULL AND (qh.qualificacao_id=qt.id OR UPPER(TRIM(COALESCE(qh.qualificacao_codigo,'')))=UPPER(TRIM(qt.codigo)))) AND COALESCE(qh.validade_meses,0)<>24;"
assert_count pt6c-hours 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND UPPER(codigo)='PT6C-67C' AND carga_horaria_inicial=16 AND carga_horaria_recorrente=8 AND ativo=1 AND deleted_at IS NULL;"
assert_count doutrinacao-mnt-hours 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND UPPER(codigo)='MNT_INTEGRACAO_DOUTRINACAO' AND carga_horaria_inicial=8 AND carga_horaria_recorrente=4 AND ativo=1 AND deleted_at IS NULL;"
assert_count nr35-non-presencial-rules 0 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND UPPER(qt.codigo)='NR-35' AND tr.ativo=1 AND tr.deleted_at IS NULL AND (COALESCE(UPPER(TRIM(tr.modalidade_requerida)),'')<>'PRESENCIAL' OR COALESCE(tr.auto_matricular_ead,0)<>0);"
assert_count nr20-non-hybrid-rules 0 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND UPPER(qt.codigo)='NR-20' AND tr.ativo=1 AND tr.deleted_at IS NULL AND (COALESCE(UPPER(TRIM(tr.modalidade_requerida)),'')<>'HIBRIDO' OR COALESCE(tr.auto_matricular_ead,0)<>0);"
assert_count nr20-nr35-autoqual 0 "SELECT COUNT(*) count FROM lms_cursos c JOIN qualificacoes_tipos qt ON qt.id=c.qualificacao_tipo_id AND qt.empresa_id=c.empresa_id WHERE c.empresa_id=6 AND UPPER(qt.codigo) IN ('NR-20','NR-35') AND c.gerar_qualificacao_ao_concluir<>0 AND c.deleted_at IS NULL;"
assert_count lgpd-not-qsms 0 "SELECT COUNT(*) count FROM qualificacoes_tipos qt LEFT JOIN qualificacoes_areas qa ON qa.id=qt.area_id AND qa.empresa_id=qt.empresa_id WHERE qt.empresa_id=6 AND UPPER(qt.codigo)='LGPD' AND (UPPER(COALESCE(qa.nome,''))<>'QSMS') AND qt.ativo=1 AND qt.deleted_at IS NULL;"
echo TRAINING_CATALOG_METADATA_REFERENCES_0533_PRODUCTION_POSTCONDITIONS=PASS
