#!/usr/bin/env bash
set -euo pipefail
umask 077
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"
ALLOWED_DB_NAME="airtrust-db"; BASELINE_ID="production-d1-baseline-v2-20260714"; CHANGE_ID="training-compliance-requirement-sanitization-0524"
target="$ALLOWED_DB_NAME"
for arg in "$@"; do case "$arg" in --target=*) target="${arg#*=}" ;; *) echo "ERROR: unknown argument: $arg" >&2; exit 1 ;; esac; done
[[ "$target" == "$ALLOWED_DB_NAME" ]] || { echo "ERROR: 0524 production postconditions refused target: $target" >&2; exit 1; }
query_count(){ local sql="$1"; (cd worker-airtrust && npx wrangler d1 execute "$target" --env production --remote --json --command "$sql") | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{const p=JSON.parse(d);const r=p[0]?.results?.[0]||{};console.log(Number(r.count??r.total??Object.values(r)[0]??0))})"; }
assert_count(){ local label="$1" expected="$2" sql="$3" count; count="$(query_count "$sql")"; [[ "$count" == "$expected" ]] || { echo "ERROR: $label expected=$expected found=$count" >&2; exit 1; }; echo "POSTCONDITION_OK=$label"; }
FDM_NAMES="'Comandante','Copiloto','Mecânico','Auxiliar de Manutenção','Coordenador de Engenharia','Analista de CTM','Analista de CTM I','Auxiliar de CTM','Auxiliar de CTM I','Gerente de Operações','Assistente de Segurança Operacional','Auxiliar de QSMS','Técnico de Segurança do Trabalho'"
assert_count schema-v2-change 1 "SELECT COUNT(*) count FROM airtrust_schema_changes_v2 WHERE change_id='$CHANGE_ID' AND baseline_id='$BASELINE_ID';"
assert_count generic-company-exclusions 0 "SELECT COUNT(*) count FROM treinamento_requisitos WHERE empresa_id=6 AND ativo=1 AND deleted_at IS NULL AND escopo='EMPRESA' AND obrigatoriedade='NAO_APLICA' AND setor_id IS NULL AND funcao_id IS NULL AND funcionario_id IS NULL AND condicao_id IS NULL AND NULLIF(TRIM(COALESCE(aeronave_modelo,'')),'') IS NULL;"
assert_count orphaned-model-rules 0 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id AND qt.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND tr.ativo=1 AND tr.deleted_at IS NULL AND (COALESCE(qt.ativo,1)<>1 OR qt.deleted_at IS NOT NULL);"
assert_count fdm-missing-reviewed-functions 0 "SELECT COUNT(*) count FROM funcoes f WHERE f.empresa_id=6 AND f.ativo=1 AND f.deleted_at IS NULL AND f.nome IN ($FDM_NAMES) AND NOT EXISTS (SELECT 1 FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo='FDM-EAD' AND tr.escopo='FUNCAO' AND tr.funcao_id=f.id AND tr.condicao_id IS NULL AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL);"
assert_count fdm-unexpected-organizational-rules 0 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id LEFT JOIN funcoes f ON f.id=tr.funcao_id WHERE tr.empresa_id=6 AND qt.codigo='FDM-EAD' AND tr.ativo=1 AND tr.deleted_at IS NULL AND tr.condicao_id IS NULL AND NOT (tr.escopo='FUNCAO' AND f.empresa_id=6 AND f.ativo=1 AND f.deleted_at IS NULL AND f.nome IN ($FDM_NAMES));"
assert_count fdm-team-condition 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id JOIN compliance_condicoes cc ON cc.id=tr.condicao_id WHERE tr.empresa_id=6 AND qt.codigo='FDM-EAD' AND cc.codigo='FDM_EQUIPE' AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count aw139-maintenance-rules 2 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id JOIN funcoes f ON f.id=tr.funcao_id WHERE tr.empresa_id=6 AND qt.codigo='MNT_AW139' AND tr.escopo='FUNCAO' AND f.nome IN ('Mecânico','Auxiliar de Manutenção') AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count aw139-unexpected-rules 0 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id LEFT JOIN funcoes f ON f.id=tr.funcao_id WHERE tr.empresa_id=6 AND qt.codigo='MNT_AW139' AND tr.ativo=1 AND tr.deleted_at IS NULL AND tr.condicao_id IS NULL AND NOT (tr.escopo='FUNCAO' AND f.nome IN ('Mecânico','Auxiliar de Manutenção')) ;"
assert_count s76-maintenance-rules 2 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id JOIN funcoes f ON f.id=tr.funcao_id WHERE tr.empresa_id=6 AND qt.codigo='MNT_S76AC' AND tr.escopo='FUNCAO' AND f.nome IN ('Mecânico','Auxiliar de Manutenção') AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count s76-unexpected-rules 0 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id LEFT JOIN funcoes f ON f.id=tr.funcao_id WHERE tr.empresa_id=6 AND qt.codigo='MNT_S76AC' AND tr.ativo=1 AND tr.deleted_at IS NULL AND tr.condicao_id IS NULL AND NOT (tr.escopo='FUNCAO' AND f.nome IN ('Mecânico','Auxiliar de Manutenção')) ;"
assert_count avsec-awareness-model 1 "SELECT COUNT(*) count FROM qualificacoes_tipos WHERE empresa_id=6 AND codigo='AVSEC_CONSC' AND ativo=1 AND deleted_at IS NULL;"
assert_count avsec-awareness-company-rule 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo='AVSEC_CONSC' AND tr.escopo='EMPRESA' AND tr.obrigatoriedade='OBRIGATORIA' AND tr.condicao_id IS NULL AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count crm-governed-exclusions-preserved 5 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id JOIN compliance_condicoes cc ON cc.id=tr.condicao_id AND cc.empresa_id=tr.empresa_id WHERE tr.empresa_id=6 AND qt.codigo='CRM_CORP' AND cc.codigo LIKE 'RBAC119_%' AND tr.obrigatoriedade='NAO_APLICA' AND tr.origem='REGULATORIO' AND tr.fundamento_tipo='PADRAO_EXCLUSAO' AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count crm-tripulacao-exclusion-preserved 1 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id JOIN setores s ON s.id=tr.setor_id WHERE tr.empresa_id=6 AND qt.codigo='CRM_CORP' AND s.codigo='TRI' AND tr.escopo='SETOR' AND tr.obrigatoriedade='NAO_APLICA' AND tr.fundamento_tipo='PROGRAMA_APROVADO' AND tr.ativo=1 AND tr.deleted_at IS NULL;"
assert_count d3-missing-rationale 0 "SELECT COUNT(*) count FROM treinamento_requisitos tr JOIN qualificacoes_tipos qt ON qt.id=tr.qualificacao_tipo_id WHERE tr.empresa_id=6 AND qt.codigo='D3' AND tr.obrigatoriedade='OBRIGATORIA' AND tr.ativo=1 AND tr.deleted_at IS NULL AND (NULLIF(TRIM(COALESCE(tr.fundamento_tipo,'')),'') IS NULL OR NULLIF(TRIM(COALESCE(tr.fundamento_documento,'')),'') IS NULL OR NULLIF(TRIM(COALESCE(tr.justificativa,'')),'') IS NULL);"
echo TRAINING_COMPLIANCE_REQUIREMENT_SANITIZATION_0524_PRODUCTION_POSTCONDITIONS=PASS