-- Migration 0366: Atualizar descrições técnicas e classificar nível de dificuldade das manobras
-- Corrige descrições que estavam ausentes, idênticas ao nome ou sem valor técnico
-- Classifica manobras com nivel_dificuldade NULL ou "-"
-- Totalmente idempotente: para descrições, só atualiza se o campo está NULL ou diferente do novo valor;
-- para dificuldade, só atualiza se NULL ou "-"

-- ============================================================
-- PARTE 1 — MANOBRAS AW139: DESCRIÇÕES TÉCNICAS
-- Condição: descricao IS NULL (SK76) ou descricao != novo_valor (idempotência)
-- ============================================================

-- Família FLY-BAS
UPDATE manobras SET descricao = 'Entrada em autorotação a partir de voo nivelado: redução de coletivo, estabalecimento de atitude de planagem e RPM de rotor dentro dos limites (Nr 90–107%); controle de velocidade de planagem (Vy ≈ 75 KIAS); flare progressivo na fase final e cushion para pouso seguro. Avaliação da prontidão de resposta e precisão de controle. (Ref: RFM AW139, Cap. 4 | FAP: FAP05.2 H7.1 — Executar autorotação)', updated_at = datetime('now') WHERE codigo = 'FLY-BAS-17' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Demonstração e avaliação do controle geral da aeronave em condições VFR: manutenção de altitude (±50 ft), velocidade (±10 kt) e proa (±10°) em voo nivelado; coordenação de controles no hover, translação e cruzeiro; resposta às entradas de comando sem oscilações. (Ref: RFM AW139, Cap. 4 | FAP: FAP05.2 H2.1)', updated_at = datetime('now') WHERE codigo = 'FLY-BAS-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Controle da aeronave com referência exclusiva a instrumentos: manutenção de altitude, velocidade e proa pelos instrumentos primários (PFD/ADI); viragens controladas sob IFR; uso correto do AP e FD como ferramentas de suporte. Tolerâncias IFR aplicadas. (Ref: RFM AW139, Cap. 4 | FAP: FAP06 IFF.2)', updated_at = datetime('now') WHERE codigo = 'FLY-BAS-X2' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de hover estacionário (OGE e IGE) com controle preciso de posição, altitude e proa; taxi em voo pairado em linha reta e com mudanças de direção; transição de hover para taxi e vice-versa. Tolerâncias: posição ±3 ft, altitude ±1 ft, proa ±5°. (Ref: RFM AW139, Cap. 4 | FAP: FAP05.2 H2.3, H3.1)', updated_at = datetime('now') WHERE codigo = 'FLY-BAS-X3' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação e recuperação de atitudes anormais (banco excessivo, cabrada/picada pronunciada) a partir de referência exclusiva de instrumentos; aplicação da técnica correta de recuperação sem agravar a situação; retorno a voo nivelado dentro dos parâmetros normais. (Ref: RFM AW139, Cap. 4 | FAP: FAP06 IFF.3)', updated_at = datetime('now') WHERE codigo = 'FLY-BAS-X4' AND (descricao IS NULL OR LENGTH(descricao) < 250);

-- Família OPS
UPDATE manobras SET descricao = 'Briefing, setup e execução de aproximação de precisão (ILS ou GLS): interceptação de localizer e glide slope, descida estabilizada com monitoramento de CDI e GS, critérios de estabilização na final (500 ft AGL), decisão na DA e pouso ou arremetida. (Ref: AIP Brasil | FAP: FAP06 IAP3.2)', updated_at = datetime('now') WHERE codigo = 'OPS-APP-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Briefing, setup e execução de aproximação não-precisão (RNAV, VOR ou NDB): descida em degraus (step-down) ou CDFA até a MDA; monitoramento de CDI/desvio lateral; decisão na MDA sem contato visual; arremetida ou pouso conforme condições. (Ref: AIP Brasil | FAP: FAP06 IAP2.2)', updated_at = datetime('now') WHERE codigo = 'OPS-APP-X2' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução da arremetida instrumental a partir de qualquer ponto da final: aplicação de potência de arremetida, subida estabilizada, captura do procedimento de aproximação perdida (APM) e comunicação com ATC. (Ref: AIP Brasil | FAP: FAP06 IAP2.3, IAP3.3)', updated_at = datetime('now') WHERE codigo = 'OPS-APP-X3' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de aproximação com ângulo acentuado (acima de 9°) para helideck ou área restrita: controle preciso de rampa de descida com alta razão de descida e velocidade reduzida; gerenciamento de potência próximo ao limite; estabilização antes do comprometimento. (Ref: RFM AW139, Cap. 4 | MGO — Operações Offshore)', updated_at = datetime('now') WHERE codigo = 'OPS-APP-X4' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Navegação combinada com FMS (Primus Epic) e meios convencionais (VOR/DME/NDB): inserção e gestão de plano de voo, cross-check de posição entre FMS e radionavegação, intercepção de radiais e execução de direct-to. Verificação cruzada PF/PM. (Ref: FMS Pilot''s Guide AW139, Cap. 4 | FAP: FAP14)', updated_at = datetime('now') WHERE codigo = 'OPS-NAV-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Seleção e gerenciamento dos modos do AP/FD (HDG, NAV, ALT, IAS, VS): ativação, monitoramento e mudança de modos em cruzeiro e fases críticas; disciplina de automação; identificação de modos armados/capturados no FMA; uso seguro dos modos de alta automação. (Ref: EPIC Guide AW139, Cap. 15 | FAP: FAP05.2 NTS1.2)', updated_at = datetime('now') WHERE codigo = 'OPS-NAV-X2' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de espera IFR com geometria correta (entrada de setor, tempo ou DME): viragem de procedimento, abeamento, pernas de afastamento e aproximação; gerenciamento de combustível no holding; saída pelo IAF ao ser liberado pelo ATC. (Ref: AIP Brasil, Seção ENR 1.5 | FAP: FAP06 CIR.7)', updated_at = datetime('now') WHERE codigo = 'OPS-NAV-X3' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de procedimento de saída padrão por instrumentos (SID) e chegada padrão (STAR): leitura correta da carta, inserção no FMS (Primus Epic), cumprimento de restrições de altitude e velocidade, comunicação com ATC em cada ponto de reporte. (Ref: AIP Brasil | FAP: FAP06 CIR.3, CIR.6)', updated_at = datetime('now') WHERE codigo = 'OPS-NAV-X4' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução disciplinada de todos os procedimentos normais de voo: checklists desafio-resposta-verificação nas fases de solo, decolagem, cruzeiro e pouso; coordenação PF/PM; fraseologia padronizada; monitoramento de parâmetros de motor e sistemas em cada fase. (Ref: QRH AW139, Normal Procedures | FAP: FAP05.2 C2.1)', updated_at = datetime('now') WHERE codigo = 'OPS-NRM-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de decolagem normal (perfil CAT B ou CAT A conforme aplicável) e pouso normal: aplicação de potência, controle de trajetória, transição, circuito e final; estabilização na aproximação (500 ft AGL); toque suave e centralizado; checklists pós-pouso. (Ref: RFM AW139, Cap. 4 | FAP: FAP05.2 H4.2, H4.3)', updated_at = datetime('now') WHERE codigo = 'OPS-NRM-X2' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de circuito de tráfego padrão (decolagem, crosswind, downwind, base e final): manutenção de altitude e velocidade em cada perna; checklists de aproximação; callouts PF/PM; estabilização na final; decisão de pouso ou arremetida. (Ref: AIP Brasil | FAP: FAP05.2 H4.2, H4.3)', updated_at = datetime('now') WHERE codigo = 'OPS-NRM-X3' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Condução de navegação em rota offshore: uso de corredor de voo, waypoints de reporte, gerenciamento de combustível vs. ponto Bingo, comunicação com agência de controle e plataforma; consciência situacional sobre Sea State e condições de vento no destino. (Ref: MGO — Operações Offshore | FAP: FAP14)', updated_at = datetime('now') WHERE codigo = 'OPS-OFF-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de aproximação ao helideck offshore: briefing de setor, vento, dimensões do deck e obstáculos; perfil de grande ângulo ou aproximação direta conforme condições; critérios de estabilização e go-around; controle de rampa e centralização sobre o "H". (Ref: RFM AW139, Cap. 4 | MGO — Operações Offshore)', updated_at = datetime('now') WHERE codigo = 'OPS-OFF-X2' AND (descricao IS NULL OR LENGTH(descricao) < 250);

-- Família WAR — AW139
UPDATE manobras SET descricao = 'Identificação da mensagem "AUX BATTERY OVERHEAT" no CAS: leitura dos itens de memória, desligamento da bateria auxiliar conforme QRH, avaliação do impacto nos sistemas dependentes e monitoramento da temperatura. (Ref: RFM AW139, Cap. 3 — Warning/Caution Procedures)', updated_at = datetime('now') WHERE codigo = 'WAR-AUX-14' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de fogo ou fumaça no compartimento de bagagem: execução imediata dos itens de memória (smoke/fire procedure), decisão de pouso imediato (land ASAP), comunicação de emergência e coordenação com cabine. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-BAG-23' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação da mensagem "MAIN BATTERY OVERHEAT" no CAS: execução dos itens de memória, avaliação da carga elétrica no barramento, desligamento da bateria principal conforme QRH e monitoramento dos sistemas afetados. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-BAT-14' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de fumaça ou fogo na cabine/cockpit: execução imediata dos itens de memória (cabin/cockpit smoke procedure); uso de oxigênio e máscara se necessário; isolamento da fonte elétrica suspeita; decisão de pouso imediato e comunicação de emergência. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-CAB-23' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação da falha do EEC (Electronic Engine Control) no CAS: leitura dos itens de memória, avaliação do comportamento do motor em modo de degradação do FADEC (EEC em modo de reversão), verificação de parâmetros de potência (ITT, Ng, torque) e continuidade do voo. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-EEC-18' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de incêndio de motor (ENGINE FIRE warning): execução imediata dos itens de memória (Engine Fire — itens sem QRH), desligamento do motor afetado, acionamento do extintor, avaliação OEI, comunicação de Pan-Pan/Mayday e pouso imediato. (Ref: RFM AW139, Cap. 3 | FAP: FAP05.2 H7.9)', updated_at = datetime('now') WHERE codigo = 'WAR-FIR-21' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de falha dos dois geradores DC (DUAL DC GEN FAIL): execução dos itens de memória, avaliação de carga na bateria (autonomia limitada), load shedding imediato, decisão de pouso imediato e comunicação de Mayday. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-GEN-11' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de emergência no trem de pouso (falha de extensão normal): tentativa de extensão pelo sistema alternativo/emergência, confirmação de indicação segura antes do pouso; briefing de pouso com trem comprometido se indicação permanecer insegura. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-GER-27' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de RPM de rotor elevado (NR HIGH): ações imediatas para redução de coletivo e controle de Nr dentro dos limites; avaliação da causa (overspeed de turbina, falha do EEC/FADEC); monitoramento contínuo pós-evento. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-HIG-29' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de motor travado no regime de marcha lenta (ENGINE STUCK IDLE): execução dos itens de memória, avaliação da capacidade de voo OEI com motor em idle, decisão de pouso imediato e gerenciamento de potência do motor operante. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-IDL-16' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de queda de RPM de rotor (NR LOW): entrada imediata de coletivo para recuperação do Nr; avaliação da causa (sobrecarga, falha de motor); prevenção de entrada em autorotação não intencional. (Ref: RFM AW139, Cap. 3 | FAP: FAP05.2 H7.1)', updated_at = datetime('now') WHERE codigo = 'WAR-LOW-29' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de pressão de óleo da MGB baixa (MGB OIL PRESSURE warning): execução dos itens de memória, redução de potência conforme limite de tempo definido no RFM (operação a seco limitada), pouso imediato e monitoramento contínuo de temperatura e pressão. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-MGB-30' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de emperramento ou resistência anormal no rotor principal (MAIN ROTOR BINDING): execução dos itens de memória, aterrissagem imediata, avaliação de vibrações anormais e comunicação com manutenção. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-MRC-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de pressão de óleo de motor baixa (OIL PRESSURE LOW warning): execução dos itens de memória, avaliação do motor afetado, redução de potência conforme procedimento, decisão de pouso imediato e monitoramento de temperatura de ITT. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-OIL-18' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de falha de motor (ENGINE FAILURE — perda de potência): execução imediata dos itens de memória OEI, manutenção de Nr, avaliação de fase do voo (hover, decolagem, cruzeiro), decisão de pouso imediato ou continuação OEI e comunicação de Pan-Pan. (Ref: RFM AW139, Cap. 3 | FAP: FAP05.2 H7.4, H7.9)', updated_at = datetime('now') WHERE codigo = 'WAR-OUT-15' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução do procedimento de desligamento de emergência de motor (EMERGENCY ENGINE SHUTDOWN): identificação da necessidade (fogo, vibração severa, falha catastrófica), execução dos itens de memória sem QRH, gerenciamento OEI e comunicação de emergência. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-SHT-19' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de obstrução da tomada estática (STATIC PORT OBSTRUCTION): reconhecimento das leituras incorretas de altímetro e velocímetro, uso de fonte estática alternativa (ALTERNATE STATIC), cross-check com instrumentos remanescentes e ajuste de procedimento de voo. (Ref: RFM AW139, Cap. 3 | FAP: FAP06 IFL.1)', updated_at = datetime('now') WHERE codigo = 'WAR-STA-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de falha do sistema de controle do rotor de cauda (TAIL ROTOR CONTROL FAILURE): execução imediata dos itens de memória, técnica de pouso com pedal travado ou inoperante, seleção de área adequada e preparação para pouso de emergência. (Ref: RFM AW139, Cap. 3 | FAP: FAP05.2 H7.6)', updated_at = datetime('now') WHERE codigo = 'WAR-TCS-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de falha do eixo de transmissão do rotor de cauda (TAIL ROTOR DRIVE FAILURE): execução dos itens de memória, técnica de autorotação com pedal ineficaz, controle de guinada via variação de coletivo e potência, pouso imediato em área adequada. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-TDR-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de temperatura elevada de óleo da MGB (MGB OIL TEMP HIGH warning): execução dos itens de memória, redução de potência para diminuir carga na transmissão, monitoramento contínuo de pressão e temperatura, pouso imediato se não houver estabilização. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-TMP-30' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de emperramento no rotor de cauda (TAIL ROTOR BINDING warning): execução dos itens de memória, aterrissagem imediata antes de ocorrer falha total, monitoramento de vibrações no pedal e comunicação com manutenção. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'WAR-TRC-X1' AND (descricao IS NULL OR LENGTH(descricao) < 250);

-- Família CAU — AW139
UPDATE manobras SET descricao = 'Identificação da mensagem "28V DC FAILURE" no CAS: leitura dos sistemas afetados pelo barramento 28V DC, cross-check de equipamentos dependentes, uso do QRH e avaliação do impacto na continuidade do voo. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-28D-58' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "DOUBLE FUEL PUMP FAILURE" no CAS: avaliação de ambas as bombas de combustível inoperantes, procedimento de alimentação por gravidade (gravity feed), monitoramento de pressão de combustível e decisão de pouso imediato. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-2FP-74' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "AC BUS FAILURE" no CAS: mapeamento dos sistemas dependentes do barramento CA (inversores, aquecimento de pitot e outros), cross-check com sistemas remanescentes, uso do QRH e avaliação do impacto operacional. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-ACB-57' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "ADC FAILURE" (Air Data Computer): reconhecimento das leituras de velocidade e altitude afetadas no PFD, uso de dados do ADC remanescente ou instrumentos de standby, cross-check entre fontes e ajuste de procedimento de voo. (Ref: RFM AW139, Cap. 3 | FAP: FAP06 IFL.1)', updated_at = datetime('now') WHERE codigo = 'CAU-ADC-48' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "ADS FAILURE" (Air Data System): avaliação do impacto nos instrumentos dependentes (IAS, altitude, VSI), transferência para sistema backup, verificação de fontes alternativas e notificação ao PM. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-ADS-46' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "AFCS DEGRADED" no CAS: avaliação de quais eixos do sistema de controle automático foram degradados, reconfiguração manual dos eixos remanescentes, aumento de carga de trabalho do piloto e decisão de continuação. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-AFD-41' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "AHRS FAILURE" (Attitude and Heading Reference System): reconhecimento das telas afetadas (PFD/MFD), uso do sistema AHRS remanescente, cross-check de atitude e proa entre sistemas e ajuste de procedimentos IFR. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-AHR-47' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "AP FAILURE" (falha do piloto automático): desengajamento do AP, retomada do controle manual, avaliação de carga de trabalho, tentativa de reengajamento conforme QRH e redistribuição de tarefas PF/PM. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-APF-37' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Procedimento de voo com AP desligado (AP OFF): manutenção manual de altitude, velocidade e proa com uso apenas do FD como referência; controle de carga de trabalho; monitoramento de parâmetros de voo sem automação. (Ref: RFM AW139, Cap. 4)', updated_at = datetime('now') WHERE codigo = 'CAU-APO-38' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "BATTERY OFFLINE" no CAS: avaliação do estado da bateria principal (offline por falha ou por proteção automática), impacto na capacidade de partida de emergência, uso do QRH e decisão de continuação ou pouso. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-BOF-55' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "COMPRESSOR NO DEMAND" no CAS: avaliação do comportamento do compressor do motor afetado fora da demanda normal, cross-check de parâmetros de motor (Ng, ITT, torque), uso do QRH e decisão de continuação ou pouso precaucional. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-CND-61' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "COMPRESSOR STALL" no CAS: reconhecimento dos sintomas (bangs, vibração, oscilação de Ng e ITT), execução dos itens de memória, redução de potência do motor afetado e avaliação da necessidade de desligamento. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-CST-59' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "DC BUS FAILURE" no CAS: mapeamento dos sistemas dependentes do barramento DC, impacto em displays, bombas e aviônicos, cross-check com barramento remanescente, uso do QRH e avaliação do impacto operacional. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-DCB-56' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "SINGLE DC GEN FAILURE" no CAS: avaliação do gerador DC inoperante, confirmação de carga no gerador remanescente, uso do QRH e monitoramento da carga elétrica total durante o voo. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-DCG-53' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "DISPLAY UNIT DEGRADED" no CAS: avaliação de qual display (PFD, MFD ou EICAS) está degradado, reconfiguração de telas para manter informação crítica visível, uso de instrumentos standby e adaptação da carga de trabalho. (Ref: RFM AW139, Cap. 3 | FAP: FAP06 IFL.1)', updated_at = datetime('now') WHERE codigo = 'CAU-DUD-46' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "ENGINE FUEL PUMP FAILURE" no CAS: avaliação da bomba de combustível do motor afetado, verificação de pressão de combustível do motor afetado, uso do QRH (procedimento de bomba inoperante), monitoramento de parâmetros de motor (ITT, Ng, torque) e decisão de continuação ou pouso. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-EFP-75' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "EICAS FAILURE" (falha do sistema integrado de alerta e indicação de motor): avaliação de quais informações de motor e sistemas ficaram indisponíveis, uso de instrumentos de backup, aumento de monitoramento manual e decisão de pouso precaucional. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-EIC-45' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "FUEL LOW" no CAS: confirmação de quantidade de combustível nos tanques, avaliação de autonomia remanescente, priorização do pouso, comunicação com ATC para prioridade e seleção do aeródromo/helideck mais próximo adequado. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-FLO-73' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "FMS FAILURE": avaliação dos sistemas de navegação remanescentes (GPS standalone, VOR/DME, NDB), reconfiguração da navegação para modo convencional, manutenção da consciência situacional sem FMS e comunicação com ATC. (Ref: RFM AW139, Cap. 3 | FAP: FAP14)', updated_at = datetime('now') WHERE codigo = 'CAU-FMS-51' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "GPS FAILURE": avaliação do impacto em navegação RNAV e aproximações GPS, transição para navegação convencional (VOR/DME/NDB), notificação ao ATC sobre perda de capacidade RNAV e seleção de procedimento alternativo de aproximação. (Ref: RFM AW139, Cap. 3 | FAP: FAP14)', updated_at = datetime('now') WHERE codigo = 'CAU-GPS-52' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de partida quente (HOT START): temperatura de ITT excedendo o limite de partida durante o acionamento; desligamento imediato do motor afetado, espera do tempo mínimo de resfriamento conforme RFM, nova tentativa com monitoramento reforçado de ITT. (Ref: RFM AW139, Cap. 2 — Engine Limitations / Normal Procedures)', updated_at = datetime('now') WHERE codigo = 'CAU-HOT-65' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "HYDRAULIC PRESSURE LOW" no CAS: avaliação do sistema hidráulico afetado (HYD 1 ou HYD 2), impacto nos servos de comando e trem de pouso, uso do QRH, limitações de velocidade aplicáveis e decisão de pouso imediato ou precaucional. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-HYP-77' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Monitoramento e gerenciamento do cronômetro de limite OEI (OEI LIMIT TIMER): reconhecimento do início da contagem ao selecionar potência de contingência, ações antes do vencimento do limite (2,5 min ou 30 min conforme RFM AW139), transição para potência contínua OEI e pouso o mais breve possível. (Ref: RFM AW139, Cap. 2 — Engine Limitations)', updated_at = datetime('now') WHERE codigo = 'CAU-LIC-60' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "MFD FAILURE": avaliação de quais informações ficaram indisponíveis (mapa, sistemas, TAWS, radar WX), reconfiguração das telas remanescentes para manter dados críticos visíveis e aumento da vigilância manual de sistemas. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-MFD-45' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "MGB CHIP DETECTED" no CAS: execução dos itens de memória, redução de potência para diminuir carga na caixa de transmissão principal, pouso imediato com monitoramento constante de temperatura e pressão de óleo da MGB. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-MGP-105' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "AP MISTRIM" no CAS: avaliação da causa do mistrim (entrada de controle, falha de sensor, carga assimétrica), recentragem dos controles, verificação de que o AP está gerenciando corretamente e monitoramento de estabilidade pós-evento. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-MIS-40' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "NG OVERSPEED" no CAS: execução imediata dos itens de memória, redução de potência do motor afetado, avaliação de danos potenciais na seção de turbina de alta pressão e decisão de pouso imediato. (Ref: RFM AW139, Cap. 2/3)', updated_at = datetime('now') WHERE codigo = 'CAU-NGO-63' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "O2 PRESSURE LOW" no CAS: avaliação da pressão do sistema de oxigênio, impacto na capacidade de uso de máscara em altitude, decisão de descida para altitude segura (abaixo de 10.000 ft) e pouso precaucional se aplicável. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-O2P-82' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "ENGINE OVERSPEED" no CAS: execução imediata dos itens de memória, redução de potência, avaliação de Ng e Nr dentro dos limites, decisão de desligamento do motor afetado se o overspeed persistir. (Ref: RFM AW139, Cap. 2/3)', updated_at = datetime('now') WHERE codigo = 'CAU-OVS-64' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "PFD FAILURE": perda do display primário de voo; transição imediata para o PFD do outro piloto ou para instrumentos de standby (ADI e altímetro de standby); redistribuição de tarefas PF/PM; aumento da carga de trabalho e ajuste de automação. (Ref: RFM AW139, Cap. 3 | FAP: FAP06 IFL.1)', updated_at = datetime('now') WHERE codigo = 'CAU-PFD-45' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "SAS DEGRADED" (Stability Augmentation System): avaliação de quais eixos do SAS estão degradados, aumento manual de precisão de controle para compensar a redução de estabilidade, reconfiguração do AFCS e monitoramento do comportamento da aeronave. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-SAS-41' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "SERVO BYPASS" no CAS: avaliação do servo afetado (cíclico, coletivo ou pedal), impacto na resposta de controle no eixo afetado, aumento de esforço manual necessário, uso do QRH e decisão de pouso. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-SRV-80' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de "THROTTLE NON-FOLLOW" no CAS: avaliação do motor com acelerador eletrônico não seguindo a demanda do FADEC (EEC), cross-check de parâmetros de motor (ITT, Ng, torque), controle manual de potência pelo acelerador físico se necessário, uso do QRH e decisão de pouso precaucional. (Ref: RFM AW139, Cap. 3)', updated_at = datetime('now') WHERE codigo = 'CAU-TNF-62' AND (descricao IS NULL OR LENGTH(descricao) < 250);

-- ============================================================
-- PARTE 2 — MANOBRAS SK76: DESCRIÇÕES TÉCNICAS
-- ============================================================

UPDATE manobras SET descricao = 'Execução dos procedimentos normais de voo VFR no SK76: acionamento, checklists, hover check, decolagem, cruzeiro VFR, circuito de tráfego e pouso; disciplina de checklist desafio-resposta; coordenação PF/PM; fraseologia padrão. (Ref: QRH SK76, Normal Procedures VFR)', updated_at = datetime('now') WHERE codigo = 'S76-NVF-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação e procedimento de partida quente no SK76: temperatura T5 excedendo o limite durante o acionamento (controlado pelo DECU); desligamento imediato, espera do tempo mínimo de resfriamento conforme RFM SK76, nova tentativa com monitoramento reforçado de T5 e registro para manutenção. (Ref: RFM SK76, Seção 2 — Engine Limitations)', updated_at = datetime('now') WHERE codigo = 'S76-HOT-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação e procedimento de falha na partida do motor no SK76: motor não atingindo parâmetros normais de partida (Ng, T5, Nr) dentro do tempo definido pelo RFM; desligamento imediato, análise da causa (elétrica, combustível, DECU) e notificação à manutenção. (Ref: RFM SK76, Seção 3 — Abnormal Procedures)', updated_at = datetime('now') WHERE codigo = 'S76-STF-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de fogo no compartimento do motor no solo no SK76: alarme de fogo em solo, desligamento de emergência do motor afetado conforme itens de memória, acionamento do extintor, evacuação imediata da aeronave e comunicação de emergência. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-FMG-08' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de fogo interno no motor após desligamento no SK76: combustão interna pós-shutdown reconhecida por fumaça ou chamas; procedimento de motoring para resfriamento (starter sem combustível); uso de extintor externo se necessário e notificação à manutenção. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-FMI-09' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de hover estacionário e táxi em voo pairado no SK76: controle preciso de posição, altitude e proa no hover (OGE e IGE); táxi em linha reta e com mudanças de direção; transição de hover para taxi e vice-versa. Tolerâncias: posição ±3 ft, altitude ±1 ft, proa ±5°. (Ref: RFM SK76, Seção 4)', updated_at = datetime('now') WHERE codigo = 'S76-HOV-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Reação à falha de motor no hover no SK76: reconhecimento imediato da perda de potência (queda de Nr, torque assimétrico), ações de memória OEI, manutenção de Nr, decisão de pouso imediato no local ou continuação OEI, gerenciamento de potência do motor remanescente e controle de contingência pelo DECU. (Ref: RFM SK76, Seção 3 | FAP: FAP05.2 H7.4)', updated_at = datetime('now') WHERE codigo = 'S76-FMH-13' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de falha do rotor de cauda no hover no SK76: perda súbita de controle de guinada no voo pairado, execução dos itens de memória (redução de coletivo, uso de inércia e translação para controle direcional), aterrissagem imediata de emergência. (Ref: RFM SK76, Seção 3 | FAP: FAP05.2 H7.6)', updated_at = datetime('now') WHERE codigo = 'S76-TRH-38' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de decolagem Classe 2 a partir de helideck offshore com definição do TDP (Takeoff Decision Point): perfil de aceleração e ascensão, reconhecimento do TDP, ações antes e após o TDP em caso de falha de motor; confirmação de V-speeds e potência planned pelo DECU. (Ref: RFM SK76, Seção 4 — Performance CAT A)', updated_at = datetime('now') WHERE codigo = 'S76-TDP-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Falha de motor antes do TDP na decolagem do SK76: reconhecimento imediato da falha (queda de T5/Ng/torque, alerta do DECU), execução do procedimento de decolagem abortada (RTO), redução de coletivo e pouso seguro na plataforma ou área de decolagem. (Ref: RFM SK76, Seção 3/4)', updated_at = datetime('now') WHERE codigo = 'S76-FMA-14' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Falha de motor após o TDP na decolagem do SK76: reconhecimento da falha após o ponto de decisão, continuação da decolagem em perfil monomotor com potência de contingência do DECU, fly-away com saída segura dos obstáculos e circuito OEI. (Ref: RFM SK76, Seção 3/4 | FAP: FAP05.2 H7.4)', updated_at = datetime('now') WHERE codigo = 'S76-FMC-15' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação e reação ao disparo do limite de Nr (Nr Overspeed) durante a subida no SK76: ações imediatas para redução de coletivo e controle de Nr dentro dos limites; avaliação da causa (overspeed de turbina, falha do DECU); monitoramento pós-evento e decisão de continuação. (Ref: RFM SK76, Seção 2/3)', updated_at = datetime('now') WHERE codigo = 'S76-NRO-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação e reação à queda de Nr (Nr Low) durante a subida no SK76: entrada imediata de coletivo para recuperação; avaliação da causa (sobrecarga, falha de motor); prevenção de entrada em autorotação não intencional e gestão de potência via DECU. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-NRL-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de estol de compressor em cruzeiro no SK76: reconhecimento dos sintomas (bangs, vibração, oscilação de T5/Ng), execução dos itens de memória, redução de potência do motor afetado e avaliação da necessidade de desligamento. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-CST-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de vibração anormal do rotor principal no SK76: avaliação da intensidade e frequência (baixa/média/alta frequência), ações conforme QRH, redução de velocidade de avanço se indicado, pouso precaucional e notificação obrigatória à manutenção. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-MRV-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de pressão de óleo da MGB entre 40–45 PSI no SK76 (faixa de cautela): leitura da indicação no painel, cross-check com temperatura de óleo da MGB, execução dos itens de memória, redução de potência conforme procedimento e pouso imediato. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-MGP-33' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação da luz de cautela do Sistema Servo Simples no SK76: avaliação do servo afetado e impacto na resposta de controle no eixo correspondente, aumento de esforço manual necessário naquele eixo, uso do QRH e decisão de continuação ou pouso precaucional. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-SSS-42' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de falha na extensão do trem de pouso no SK76: tentativa de extensão pelo sistema de emergência, confirmação de indicação segura antes do pouso, briefing de pouso com trem comprometido se indicação insegura persistir. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-LGE-44' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Entrada em autorotação no SK76 a partir de voo nivelado: redução de coletivo, estabalecimento de atitude de planagem e Nr dentro dos limites; controle de velocidade de planagem (Vy conforme peso e altitude — consultar tabelas do RFM SK76); flare progressivo e cushion para pouso seguro. (Ref: RFM SK76, Seção 4 | FAP: FAP05.2 H7.1)', updated_at = datetime('now') WHERE codigo = 'S76-AUT-70' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução de pouso Classe 2 em helideck com definição do LDP (Landing Decision Point / Committal Point): perfil de aproximação final, reconhecimento do LDP, ações antes e após o LDP em caso de falha de motor; confirmação de potência disponível para go-around monomotor antes do comprometimento com o pouso. (Ref: RFM SK76, Seção 4)', updated_at = datetime('now') WHERE codigo = 'S76-LDP-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução do circuito de tráfego padrão noturno (NDL — Night Deck Landing) no SK76: decolagem noturna, circuito com referências de iluminação da plataforma, downwind, base e final noturnos; estabilização na aproximação; pouso no helideck com referência primária na iluminação perimetral e no "H". (Ref: MGO — Operações Noturnas | RFM SK76, Seção 4)', updated_at = datetime('now') WHERE codigo = 'S76-NDL-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação da luz de cautela do filtro de combustível no SK76: avaliação de filtro obstruído (ice, contaminação), impacto na pressão de combustível do motor afetado, uso do QRH (ativação do by-pass do filtro se disponível) e decisão de pouso precaucional. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-FFL-32' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de fluxo de combustível fora do normal no SK76: avaliação de consumo excessivo ou insuficiente no IIDS, cross-check entre tanques, investigação de possível vazamento ou falha do DECU no controle de combustível e decisão de pouso. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-FFM-32' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação da luz de cautela Battery Off no SK76: avaliação do estado da bateria (offline por falha ou proteção), impacto na capacidade de partida de emergência e sistemas de backup, uso do QRH e decisão de continuação ou pouso precaucional. (Ref: RFM SK76, Seção 3)', updated_at = datetime('now') WHERE codigo = 'S76-BTO-51' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Identificação de falha do Radio Master no SK76: avaliação dos rádios inoperantes, tentativa de reativação, uso de rádio alternativo (se disponível), perda de comunicação com ATC e procedimentos de voo em silêncio de rádio (NORDO) conforme AIP Brasil. (Ref: RFM SK76, Seção 3 | AIP Brasil — Procedimentos NORDO)', updated_at = datetime('now') WHERE codigo = 'S76-RMF-69' AND (descricao IS NULL OR LENGTH(descricao) < 250);
UPDATE manobras SET descricao = 'Execução dos procedimentos normais de voo IFR no SK76: acionamento, checklists, configuração de aviônica (Primus 701), decolagem IFR, navegação por FMS e rádionavegação, procedimento de aproximação por instrumentos, decisão na DA/MDA e pouso ou arremetida. (Ref: QRH SK76, Normal Procedures IFR | Primus 701 Guide)', updated_at = datetime('now') WHERE codigo = 'S76-NIF-00' AND (descricao IS NULL OR LENGTH(descricao) < 250);

-- ============================================================
-- PARTE 3 — CLASSIFICAR NÍVEL DE DIFICULDADE (nivel_dificuldade)
-- Apenas para manobras operacionais com NULL ou "-"
-- Grupos EXA, INV, LOFT-CHK/NOT/OFF são LOFT/procedimentais — NÃO alterar
-- ============================================================

UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'WAR-SHT-19' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'BASICO', updated_at = datetime('now') WHERE codigo = 'S76-NVF-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-HOT-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-STF-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-FMG-08' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-FMI-09' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'BASICO', updated_at = datetime('now') WHERE codigo = 'S76-HOV-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-FMH-13' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-TRH-38' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-TDP-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-FMA-14' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-FMC-15' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-NRO-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-NRL-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-CST-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-MRV-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-MGP-33' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-SSS-42' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-LGE-44' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'AVANCADO', updated_at = datetime('now') WHERE codigo = 'S76-AUT-70' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-LDP-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-NDL-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-FFL-32' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-FFM-32' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-BTO-51' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-RMF-69' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
UPDATE manobras SET nivel_dificuldade = 'INTERMEDIARIO', updated_at = datetime('now') WHERE codigo = 'S76-NIF-00' AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');

-- ============================================================
-- VALIDAÇÃO PÓS-MIGRATION (executar manualmente após rodar a migration)
-- ============================================================

-- 1. Nenhuma manobra AW139 menciona "DECU" na descrição
-- SELECT codigo, nome FROM manobras WHERE tipo_aeronave = 'AW139' AND LOWER(descricao) LIKE '%decu%';
-- Esperado: 0 linhas

-- 2. CAU-TNF-62 usa FADEC/EEC, não DECU
-- SELECT codigo, descricao FROM manobras WHERE codigo = 'CAU-TNF-62';
-- Esperado: descrição deve conter "FADEC" ou "EEC", NÃO "DECU"

-- 3. CAU-HOT-65 usa ITT e não TGT
-- SELECT codigo, descricao FROM manobras WHERE codigo = 'CAU-HOT-65';
-- Esperado: descrição deve conter "ITT", NÃO "TGT"

-- 4. WAR-EEC-18 não menciona "DECU"
-- SELECT codigo, descricao FROM manobras WHERE codigo = 'WAR-EEC-18';
-- Esperado: descrição contém "EEC" e/ou "FADEC", NÃO "DECU"

-- 5. Manobras SK76 com DECU corretamente referenciado
-- SELECT codigo, descricao FROM manobras WHERE tipo_aeronave = 'SK76' AND LOWER(descricao) LIKE '%decu%';
-- Esperado: apenas manobras SK76 (correto)

-- 6. WAR-SHT-19 classificada
-- SELECT codigo, nivel_dificuldade FROM manobras WHERE codigo = 'WAR-SHT-19';
-- Esperado: AVANCADO

-- 7. Todas as manobras SK76 operacionais classificadas
-- SELECT codigo, nivel_dificuldade FROM manobras
-- WHERE tipo_aeronave = 'SK76'
-- AND codigo NOT LIKE 'S76-LOFT-%'
-- AND (nivel_dificuldade IS NULL OR nivel_dificuldade = '-');
-- Esperado: 0 linhas

-- 8. Contagem total de manobras inalterada
-- SELECT COUNT(*) FROM manobras;
-- (comparar com contagem antes da migration)
