-- source_reference: Petrobras planilha de codigos de atrasos dos voos, fornecida pelo usuario em 2026-09-20.
-- operational_decision: seed canonical AA41-AA94 delay justification catalog for empresa_id 6, preserving source categories and descriptions; searchable by code, name, category and description.
-- dry_run_required: validate additive category column, 54 canonical rows, tenant isolation and zero mutation outside empresa_id 6.
-- rollback_plan_required: additive category column remains; seeded rows can be inactivated/compensated by exact code if application rollback is required.

ALTER TABLE cv_justificativas_voo ADD COLUMN categoria TEXT;

CREATE INDEX IF NOT EXISTS idx_cv_justificativas_voo_empresa_categoria
  ON cv_justificativas_voo (empresa_id, categoria, ordem)
  WHERE deleted_at IS NULL;

INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA41', 'ABASTECIMENTO', 'Empresa Aérea', NULL, 1, 41, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA42', 'INDISP. DE EQP. DE SUPORTE DA CIA AÉREA', 'Empresa Aérea', 'Falta de GPU, carrinho de bagagens, reboque e outros.', 1, 42, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA43', 'REGULAMENTAÇÃO DE CONTRATOS DE 12/24H', 'Empresa Aérea', 'A regulamentação para contratos de 12 horas exige limites para período de descanso ou almoço/jantar de 1h de duração entre 11h00 e 14h00 ou entre 19h às 21:30h.', 1, 43, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA44', 'INDISP. NO SISTEMA DA EMPRESA AÉREA', 'Empresa Aérea', 'Sistemas da empresa aérea fora de operação ou sistemas não pertencentes à Petrobras.', 1, 44, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA45', 'ATRASO CAUSADO PELA EMPRESA', 'Empresa Aérea', 'Ausência de despachante e outros profissionais; demora no cálculo da disponibilidade da aeronave, falta de diligenciamento transporte interno, conversão configuração da aeronave, outras causas.', 1, 45, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA46', 'PROCESSAMENTO DE PASSAGEIROS', 'Empresa Aérea', 'Check-in; briefing; sala de embarque; canal de inspeção; pesagem dos passageiros; despacho de celulares e eletrônicos; impacto de voo comercial.', 1, 46, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA47', 'APRESENTAÇÃO/INDISP. DE TRIPULANTES', 'Empresa Aérea', NULL, 1, 47, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA48', 'INDISP. DE AERONAVE POR MANUT. BRISTOW', 'Empresa Aérea', 'Manutenções; indisponibilidade em aeronaves da Bristow.', 1, 48, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA49', 'INDISP. DE AERONAVE POR MANUTENÇÃO CHC', 'Empresa Aérea', 'Manutenções; indisponibilidade em aeronaves da CHC.', 1, 49, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA50', 'INDISP. DE AERO. POR MANUT. COSTA DO SOL', 'Empresa Aérea', 'Manutenções; indisponibilidade em aeronaves da Costa do Sol.', 1, 50, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA51', 'INDISP. DE AERONAVE POR MANUTENÇÃO LIDER', 'Empresa Aérea', 'Manutenções; indisponibilidade em aeronaves da Lider.', 1, 51, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA52', 'INDISP. DE AERONAVE POR MANUTENÇÃO OMNI', 'Empresa Aérea', 'Manutenções; indisponibilidade em aeronaves da Omni.', 1, 52, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA53', 'SOLICITAÇÃO DA UNIDADE MARÍTIMA', 'Solicitação da Unidade Marítima', 'Aguardando liberação da unidade para início do atendimento; Aguardando passageiro com atraso solicitado pelo cliente.', 1, 53, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA54', 'CHEGADA DE PAX DE COMITIVA', 'Solicitação da Unidade Marítima', NULL, 1, 54, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA55', 'INTERCORRÊNCIAS RELACIONADAS A CARGA', 'Solicitação da Unidade Marítima', 'Atraso a apresentação ou inclusão de cargas no voo gerando atraso no check-in.', 1, 55, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA56', 'ENVIO DO BOLETIM METEOROLÓGICO', 'Solicitação da Unidade Marítima', 'Atraso na emissão do boletim meteorológico.', 1, 56, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA57', 'PAX EM AVALIAÇÃO MÉDICA', 'Solicitação da Unidade Marítima', NULL, 1, 57, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA58', 'LIBERAÇÃO DE HELIPONTO', 'Solicitação da Unidade Marítima', 'Aeronave cortada na unidade devido a comitivas ou resgate aeromédico e outras situações operacionais; SLO obstruído; Análise de Acoplamento; Heliponto suspenso pelo SCA ou Órgão Regulador.', 1, 58, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA59', 'TRANSPORTE EXTERNO DE PAX CONTRATADOS', 'Solicitação da Unidade Marítima', 'Aguardando ônibus, van com passageiros contratados ou veículos particulares de contratados.', 1, 59, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA60', 'INDISP. NO SISTEMA RÁDIO TELEFONIA DA UM', 'Solicitação da Unidade Marítima', NULL, 1, 60, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA61', 'ENVIO DO MANIFESTO DE DESEMBARQUE', 'Solicitação da Unidade Marítima', 'Atraso de emissão do manifesto de transporte aéreo de desembarque.', 1, 61, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA62', 'TEMPO DE VOO MAIOR QUE O PROGRAMADO', 'Necessidade Operacional', 'Intervalo entre o término do voo anterior e o início do próximo voo inferior a 45 minutos devido a movimentação de embarcações ou tempo de voo no SITAER desatualizado ou similar.', 1, 62, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA63', 'NOVA LEITURA DO HMS', 'Necessidade Operacional', 'Situações em que as condições do mar estão no limite permitido para pouso na unidade marítima ou embarcação, e uma nova leitura pode indicar viabilidade para o pouso.', 1, 63, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA64', 'PAX C/ MAL-ESTAR/NECESSID. FISIOLÓGICAS', 'Necessidade Operacional', 'Passageiros que necessitam de atendimento médico ou de enfermagem após ingressarem na área restrita (lado ar) ou necessitam utilizar instalações sanitárias.', 1, 64, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA65', 'EXCLUSÃO DE POUSOS', 'Necessidade Operacional', 'Exclusão de pouso(s) nas Unidades Marítimas ou Embarcações.', 1, 65, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA66', 'INCLUSÃO DE POUSOS', 'Necessidade Operacional', 'Inclusão de pouso(s) nas Unidades Marítimas ou Embarcações.', 1, 66, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA67', 'INCLUSÃO DE PASSAGEIRO(S)', 'Necessidade Operacional', 'Inclusão de passageiros podendo gerar ou não a mudança de prefixo de aeronave.', 1, 67, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA68', 'EXCLUSÃO DE PAX POR EXCESSO DE PESO', 'Necessidade Operacional', 'Transferência de passageiros devido a excesso de peso podendo ou não gerar a mudança do prefixo de aeronave.', 1, 68, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA69', 'EXCLUSÃO DE PAX VOO IFR OU TEMP. ALTA', 'Necessidade Operacional', 'Pax retirado por excesso de peso devido a voo por instrumentos ou temperatura elevada.', 1, 69, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA70', 'CONFIGURAÇÃO DA AERONAVE TRANSFORMER', 'Necessidade Operacional', 'Aguardando desconfiguração da aeronave transformer para pax ou vice versa.', 1, 70, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA71', 'AUDITORIA PETROBRAS (ACC)', 'Necessidade Operacional', 'Aguardando a aeronave que passou do tempo planejado para vistoria, que não pode ser prorrogada, impossibilitando sua programação no trilho.', 1, 71, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA72', 'MUDANÇA DE PREFIXO DA AERONAVE', 'Necessidade Operacional', 'Mudança de prefixo da aeronave por necessidade operacional e para otimização do atendimento.', 1, 72, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA73', 'DESMEMBRAMENTO E ANEXAÇÃO DE VOO', 'Necessidade Operacional', 'Desmembramento de voo para otimização do atendimento; anexação de voo.', 1, 73, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA74', 'OVERBOOKING ACÚMULO TRANSF. DIA ANTERIOR', 'Necessidade Operacional', 'Voos programados maior que a capacidade operacional; acúmulo de voos devido transferências do dia anterior.', 1, 74, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA75', 'TRANSPORTE ROTA FIXA PETROBRAS', 'Necessidade Operacional', 'Aguardando ônibus com passageiros Petrobras; aguardando manifestação ou acidente na rodovia, impossibilitando a passagem dos veículos.', 1, 75, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA76', 'CONFIGURAÇÃO DA AERONAVE CARGUEIRA', 'Necessidade Operacional', 'Aguardando configuração da aeronave para receber carga quando a mesma está em voo de passageiros ou vice-versa.', 1, 76, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA77', 'INDISPONIBILIDADE EM SISTEMAS PETROBRAS', 'Necessidade Operacional', 'Sistemas fora do ar (SAP, SITAER, SEGPRO e outros sistemas da Petrobras).', 1, 77, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA78', 'INCLUSÃO DE POUSO IMPACTA VOO SEGUINTE', 'Necessidade Operacional', 'Aumento do tempo do voo anterior gerado pela inclusão de pouso e/ou passageiro que impacta o voo seguinte afetando o tempo total do atendimento.', 1, 78, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA79', 'INSPEÇÃO DE ÓRGÃO REGULADOR', 'Necessidade Operacional', 'Atraso causado por inspeção de órgãos como ANAC, DECEA, entre outros.', 1, 79, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA80', 'VOOS NA MESMA UM COM INTERVALO < 15 MIN', 'Necessidade Operacional', 'Considerar intervalos curtos como voos programados menores que 15 minutos.', 1, 80, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA81', 'SOLICITAÇÃO DA FISCALIZAÇÃO PETROBRAS', 'Necessidade Operacional', 'Solicitações extraordinárias da fiscalização Petrobras.', 1, 81, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA82', 'PROGRAMAÇÃO PETROBRAS INEXEQUÍVEL DO VOO', 'Necessidade Operacional', 'Programação originalmente realizada sem possibilidade de execução do voo no horário programado.', 1, 82, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA83', 'PAX EM REUNIÃO COM SINDICATO', 'Necessidade Operacional', NULL, 1, 83, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA84', 'OBRAS NO AEROPORTO', 'Gestão Aeroportuária', NULL, 1, 84, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA85', 'INFRAESTRUTURA DO AEROPORTO', 'Gestão Aeroportuária', 'Aeronave em hangar/box - excesso de aeronaves nas áreas de estacionamento.', 1, 85, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA86', 'FALTA DE ENERGIA NO AEROPORTO', 'Gestão Aeroportuária', NULL, 1, 86, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA87', 'INDISP. DO SISTEMA DE RADAR E FREQUÊNCIA', 'Gestão Aeroportuária', 'Radar inoperante; frequência 120 inoperante (comunicação fora do ar entre EPTA’s e a INFRAERO); ADSB.', 1, 87, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA88', 'LIBERAÇÃO DO PLANO DE VOO', 'Gestão Aeroportuária', 'Aguardando a autorização do plano de voo pelo sistema Sigma e afins.', 1, 88, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA89', 'AUTORIZAÇÃO DA TORRE DE CONTROLE', 'Gestão Aeroportuária', 'Tráfego intenso de pousos e decolagens; objetos ou animais na pista.', 1, 89, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA90', 'INTERDIÇÃO DO AERÓDROMO', 'Gestão Aeroportuária', 'Aeroporto interditado pelo gestor aeroportuário ou órgão fiscalizador.', 1, 90, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA91', 'TRANSPORTE INTERNO AEROPORTO', 'Gestão Aeroportuária', 'Aguardando ônibus/van para levar os passageiros até a aeronave; Aguardando transporte interno do aeroporto.', 1, 91, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA92', 'CONDIÇÕES METEOROLÓGICAS NA UM', 'Condições Meteorológicas', 'Condições de mar (balanço das unidades marítimas); condições de tempo (chuva, nevoeiro).', 1, 92, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA93', 'CONDIÇÕES METEOROLÓGICAS NO AEROPORTO', 'Condições Meteorológicas', 'Condições de tempo (chuva, nevoeiro) no aeroporto de origem ou sem aeroporto alternativo.', 1, 93, datetime('now'), datetime('now'));
INSERT INTO cv_justificativas_voo (empresa_id, codigo, nome, categoria, descricao, ativo, ordem, created_at, updated_at) VALUES (6, 'AA94', 'CONDIÇÕES METEOROLÓGICAS NA ROTA', 'Condições Meteorológicas', 'Condições de tempo (chuva, nevoeiro) na rota entre o aeroporto e a unidade marítima ou vice-versa.', 1, 94, datetime('now'), datetime('now'));
