#!/bin/bash

# ============================================================
# SCRIPT DE INSTALAÇÃO DO MÓDULO DE LICENÇAS
# ============================================================
# 
# Este script aplica a migration da tabela licencas no D1 de produção
# usando o Cloudflare Dashboard (método manual alternativo ao wrangler)
#
# INSTRUÇÃO PASSO A PASSO:
# ============================================================

echo "════════════════════════════════════════════════════════════"
echo "  📋 INSTALAÇÃO DO MÓDULO DE LICENÇAS - PASSO A PASSO"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  A migration não pôde ser aplicada via wrangler devido a"
echo "   permissões de API. Você precisa aplicar manualmente via"
echo "   Cloudflare Dashboard."
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  PASSO 1: Acessar Cloudflare Dashboard"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Acesse: https://dash.cloudflare.com"
echo "2. Faça login com suas credenciais"
echo "3. Navegue para: Workers & Pages → D1"
echo "4. Clique em: airtrust-db"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  PASSO 2: Abrir Console SQL"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "5. Clique na aba 'Console'"
echo "6. No campo de texto SQL, cole o conteúdo abaixo:"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  📝 SQL DA MIGRATION (copie e cole):"
echo "════════════════════════════════════════════════════════════"
echo ""

cat migrations/005_licencas_completo.sql

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  PASSO 3: Executar Migration"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "7. Clique em 'Execute'"
echo "8. Aguarde a confirmação de sucesso"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  PASSO 4: Validar Instalação"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "9. Execute este comando para validar:"
echo ""
echo "   curl -s 'https://airtrust.airtrust.workers.dev/api/licencas' | jq '.success'"
echo ""
echo "10. Se retornar 'true', a instalação está completa! ✅"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  📊 APÓS A INSTALAÇÃO"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ Acesse o sistema: https://production.airtrust.pages.dev"
echo "✅ Vá para: Qualificações → Aba 'Licenças'"
echo "✅ Adicione licenças e teste os filtros"
echo "✅ Verifique o dashboard com métricas"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  🎉 MÓDULO DE LICENÇAS - FUNCIONALIDADES"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 API Completa:"
echo "   • GET    /api/licencas             (lista com filtros)"
echo "   • GET    /api/licencas/:id         (busca por ID)"
echo "   • POST   /api/licencas             (criar)"
echo "   • PUT    /api/licencas/:id         (atualizar)"
echo "   • DELETE /api/licencas/:id         (soft delete)"
echo "   • GET    /api/dashboard/licencas   (métricas)"
echo ""
echo "🎨 UI Implementada:"
echo "   • Aba 'Licenças' em Qualificações"
echo "   • Dashboard com 4 cards (Total, Válidas, A Vencer, Vencidas)"
echo "   • Tabela avançada com status visual"
echo "   • Filtros: Tipo, Status, Busca"
echo "   • Modal create/edit completo"
echo "   • Integração no Modal de Funcionário"
echo ""
echo "🔧 Tipos de Licença Suportados:"
echo "   • CMA   - Certificado Médico Aeronáutico"
echo "   • CANAC - Código ANAC"
echo "   • CHT   - Certificado de Habilitação Técnica"
echo "   • PP    - Piloto Privado"
echo "   • PC    - Piloto Comercial"
echo "   • PLA   - Piloto de Linha Aérea"
echo "   • IFR   - Instrumento"
echo "   • INVA  - Instrutor de Voo - Avião"
echo "   • INVH  - Instrutor de Voo - Helicóptero"
echo "   • MLTE  - Multi-Engine Land"
echo "   • MNTE  - Multi-Engine Night"
echo "   • OUTRO - Outros tipos"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "💡 DICA: Salve este script para referência futura!"
echo ""
echo "════════════════════════════════════════════════════════════"
