#!/bin/bash

echo "🧹 Limpando cache do navegador e service workers..."

# Instruções para limpar cache no navegador
echo ""
echo "📋 INSTRUÇÕES PARA LIMPAR CACHE:"
echo ""
echo "1. No Chrome/Edge/Brave:"
echo "   - Pressione: Cmd + Shift + Delete"
echo "   - Ou vá em: Configurações > Privacidade > Limpar dados de navegação"
echo "   - Marque: 'Imagens e arquivos em cache'"
echo "   - Período: 'Última hora'"
echo "   - Clique em 'Limpar dados'"
echo ""
echo "2. Depois, force um hard refresh:"
echo "   - Pressione: Cmd + Shift + R"
echo "   - Ou: Cmd + Option + R"
echo ""
echo "3. Se ainda não funcionar, abra o DevTools:"
echo "   - Pressione: Cmd + Option + I"
echo "   - Vá na aba 'Application'"
echo "   - Clique em 'Service Workers'"
echo "   - Clique em 'Unregister' em todos os service workers"
echo "   - Clique em 'Clear storage' > 'Clear site data'"
echo ""
echo "4. Feche e reabra o navegador completamente"
echo ""
echo "✅ Depois de fazer isso, tente o upload novamente!"
