export type TrainingDependencyQualificationRow = {
  funcionario_id: number;
  funcionario_nome: string;
  funcionario_funcao: string | null;
  qualificacao_tipo_id: number;
  qualificacao_codigo: string | null;
  qualificacao_nome: string;
  data_vencimento: string;
  cycle_start_date: string | null;
  planning_source: 'TRAINING_DEPENDENCY';
  source_planning_id: number;
};

async function tableExists(db: D1Database, tableName: string): Promise<boolean> {
  const row = await db
    .prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?")
    .bind(tableName)
    .first<{ name: string }>();
  return row?.name === tableName;
}

/**
 * Exposes open qualification obligations generated by treinamento_dependencias
 * to the Simulator Planning V2 pipeline. The dependency row is only the durable
 * obligation/audit anchor: the planner still resolves the complete current
 * curriculum from modelos_sessao, so it never trusts a stale one-session snapshot.
 */
export async function loadPendingTrainingDependencyQualifications(params: {
  db: D1Database;
  empresaId: number;
  inicio: string;
  fim: string;
  scopeClause: string;
  scopeBindings: number[];
  qualificationTypeIds: number[];
}): Promise<TrainingDependencyQualificationRow[]> {
  if (params.qualificationTypeIds.length === 0) return [];
  if (!(await tableExists(params.db, 'treinamento_dependencias'))) return [];
  if (!(await tableExists(params.db, 'treinamentos_planejados'))) return [];

  const placeholders = params.qualificationTypeIds.map(() => '?').join(', ');
  const rows = await params.db
    .prepare(
      `SELECT f.id AS funcionario_id,
              f.nome AS funcionario_nome,
              f.funcao AS funcionario_funcao,
              qt.id AS qualificacao_tipo_id,
              qt.codigo AS qualificacao_codigo,
              qt.nome AS qualificacao_nome,
              t.planejamento_vencimento_referencia AS data_vencimento,
              CAST(json_extract(t.planejamento_snapshot_json, '$.dependency.source_completion_date') AS TEXT)
                AS cycle_start_date,
              'TRAINING_DEPENDENCY' AS planning_source,
              t.id AS source_planning_id
         FROM treinamentos_planejados t
         INNER JOIN treinamentos_participantes tp
           ON tp.treinamento_id = t.id
         INNER JOIN funcionarios f
           ON f.id = tp.funcionario_id
          AND f.empresa_id = t.empresa_id
          AND f.deleted_at IS NULL
          AND COALESCE(f.ativo, 1) = 1
         INNER JOIN qualificacoes_tipos qt
           ON qt.id = t.qualificacao_tipo_id
          AND qt.empresa_id = t.empresa_id
          AND qt.deleted_at IS NULL
          AND COALESCE(qt.ativo, 1) = 1
        WHERE t.empresa_id = ?
          AND t.deleted_at IS NULL
          AND t.planejamento_origem = 'SIMULADOR_QUINZENA'
          AND t.planejamento_status IN (
            'PROPOSTO', 'PLANEJADO', 'AGUARDANDO_DISPONIBILIDADE', 'CONFIRMADO', 'REPLANEJAR'
          )
          AND t.planejamento_vencimento_referencia IS NOT NULL
          AND date(t.planejamento_vencimento_referencia) BETWEEN date(?) AND date(?)
          AND t.qualificacao_tipo_id IN (${placeholders})
          AND json_valid(t.planejamento_snapshot_json) = 1
          AND (
            json_extract(t.planejamento_snapshot_json, '$.generated_by') = 'TRAINING_DEPENDENCY'
            OR json_extract(t.planejamento_snapshot_json, '$.dependency.rule_id') IS NOT NULL
          )
          AND ${params.scopeClause}
          AND NOT EXISTS (
            SELECT 1
              FROM qualificacoes_historico qh_done
             WHERE qh_done.empresa_id = t.empresa_id
               AND qh_done.funcionario_id = f.id
               AND qh_done.qualificacao_id = t.qualificacao_tipo_id
               AND qh_done.deleted_at IS NULL
               AND UPPER(COALESCE(qh_done.status, '')) = 'CONCLUIDA'
               AND qh_done.data_conclusao IS NOT NULL
               AND date(qh_done.data_conclusao) >= date(
                 COALESCE(
                   CAST(json_extract(t.planejamento_snapshot_json, '$.dependency.source_completion_date') AS TEXT),
                   '0001-01-01'
                 )
               )
          )
        ORDER BY date(t.planejamento_vencimento_referencia), f.nome, qt.nome, t.id`,
    )
    .bind(
      params.empresaId,
      params.inicio,
      params.fim,
      ...params.qualificationTypeIds,
      ...params.scopeBindings,
    )
    .all<TrainingDependencyQualificationRow>();

  return (rows.results || []).map((row) => ({
    ...row,
    funcionario_id: Number(row.funcionario_id),
    qualificacao_tipo_id: Number(row.qualificacao_tipo_id),
    source_planning_id: Number(row.source_planning_id),
    data_vencimento: String(row.data_vencimento).slice(0, 10),
    cycle_start_date: row.cycle_start_date ? String(row.cycle_start_date).slice(0, 10) : null,
    planning_source: 'TRAINING_DEPENDENCY',
  }));
}
