import { resolveOperationalPolicyV2 } from '../../lib/frms/operational-policy-v2';

export const V2_VALUES: Record<string, number> = {
  FRMS_V2_ENABLED: 1,
  LANDINGS_NEUTRAL_MAX: 8, LANDINGS_PENALTY_PER_EXCESS: .5, LANDINGS_PENALTY_CAP_POINTS: 4,
  TEMP_BAND1_MIN_C: 30, TEMP_BAND2_MIN_C: 32, TEMP_BAND3_MIN_C: 34, TEMP_BAND4_MIN_C: 36,
  TEMP_BAND1_DELTA_POINTS: -.5, TEMP_BAND2_DELTA_POINTS: -1, TEMP_BAND3_DELTA_POINTS: -1.5, TEMP_BAND4_DELTA_POINTS: -2, TEMP_PENALTY_CAP_POINTS: 2,
  IMC_VISIBILITY_THRESHOLD_M: 5000, IMC_CEILING_THRESHOLD_FT: 1500,
  IMC_DEPARTURE_DELTA_POINTS: -.5, IMC_ARRIVAL_DELTA_POINTS: -.75, IMC_LEG_CAP_POINTS: 1, IMC_DAY_CAP_POINTS: 3,
  RECOVERY_HOTEL_MAX_POINTS: 4, RECOVERY_ONSITE_MAX_POINTS: 1.5, RECOVERY_IMMEDIATE_CALLOUT_MULTIPLIER: .75,
  RECOVERY_NO_WORK_MIN_HOURS: 12, RECOVERY_ABSOLUTE_REST_MIN_HOURS: 4, RECOVERY_ABSOLUTE_REST_MID_HOURS: 6,
  RECOVERY_ABSOLUTE_REST_FULL_HOURS: 8, RECOVERY_ABSOLUTE_REST_LOW_FACTOR: .5, RECOVERY_ABSOLUTE_REST_MID_FACTOR: .75,
  HV_CREDIT_THRESHOLD_MINUTES: 120, HV_CREDIT_MAX_POINTS: 2, HV_NEUTRAL_MAX_MINUTES: 420,
  HV_PENALTY_PER_EXCESS_HOUR_POINTS: 2, HV_PENALTY_CAP_POINTS: 4,
  PRESENTATION_NIGHT_START_HOUR: 22, PRESENTATION_NIGHT_END_HOUR: 2, PRESENTATION_NIGHT_DELTA_POINTS: -.5,
  ACCUMULATION_WINDOW_MODE: 0, ACCUMULATION_USE_MONTH_CALENDAR: 1, ACCUMULATION_USE_YEAR_CALENDAR: 1,
  ACCUMULATION_USE_28D_ROLLING: 0, ACCUMULATION_USE_365D_ROLLING: 0,
};

export const V2_POLICY = resolveOperationalPolicyV2(V2_VALUES);
export const V2_POLICY_VERSION = 'FRMS_OPERATIONAL_POLICY_V2_TEST';
