import type {
  EscalaAlocacao,
  EscalaCoberturaTripulante,
  EscalaEvento,
} from '../../hooks/queries/useEscalasQuery';

export function isAlocacaoOperacionalComAeronave(alocacao: EscalaAlocacao): boolean {
  if (alocacao.situacao_tipo) return false;

  return Boolean(
    alocacao.aeronave_id != null ||
    alocacao.aeronave_prefixo ||
    alocacao.aeronave?.prefixo ||
    alocacao.aeronave_modelo ||
    alocacao.aeronave?.modelo,
  );
}

function overlapsPeriodo(
  dataInicio: string,
  dataFim: string,
  intervaloInicio: string,
  intervaloFim: string,
) {
  return !(dataFim < intervaloInicio || dataInicio > intervaloFim);
}

function getAlocacaoVisualPrioridade(alocacao: EscalaAlocacao): number {
  const situacaoTipo = alocacao.situacao_tipo as string | null | undefined;

  if (situacaoTipo === 'FERIAS') return 0;
  if (
    situacaoTipo === 'SIM' ||
    situacaoTipo === 'CURSO' ||
    situacaoTipo === 'MED' ||
    situacaoTipo === 'AFT'
  ) {
    return 1;
  }
  if (isAlocacaoOperacionalComAeronave(alocacao)) return 2;
  if (situacaoTipo === 'STB') return 3;
  if (situacaoTipo === 'FOLGA') return 4;
  return 5;
}

export function chooseTripulanteDayAlocacao(
  alocacoes: EscalaAlocacao[],
  diaIso: string,
): EscalaAlocacao | null {
  return alocacoes.reduce<EscalaAlocacao | null>((melhor, atual) => {
    const ativaNoDia = atual.data_inicio <= diaIso && atual.data_fim >= diaIso;
    if (!ativaNoDia) return melhor;
    if (!melhor) return atual;

    const prioridadeAtual = getAlocacaoVisualPrioridade(atual);
    const prioridadeMelhor = getAlocacaoVisualPrioridade(melhor);
    if (prioridadeAtual !== prioridadeMelhor) {
      return prioridadeAtual < prioridadeMelhor ? atual : melhor;
    }

    const atualManual = !(atual.auto_gerado === 1 || atual.auto_gerado === true);
    const melhorManual = !(melhor.auto_gerado === 1 || melhor.auto_gerado === true);
    if (atualManual !== melhorManual) {
      return atualManual ? atual : melhor;
    }

    return atual.updated_at > melhor.updated_at ? atual : melhor;
  }, null);
}

export function isOppositeTripulanteQuinzenaDay(
  tripulanteQuinzena: number | null | undefined,
  quinzenaNumero: 1 | 2,
): boolean {
  if (tripulanteQuinzena !== 1 && tripulanteQuinzena !== 2) {
    return false;
  }

  return tripulanteQuinzena !== quinzenaNumero;
}

/**
 * Mapping from escala_eventos.tipo_evento to the corresponding
 * escala_alocacoes.situacao_tipo and display color.
 * Events synced from external modules (simuladores, funcionarios) appear only
 * in escala_eventos — not in escala_alocacoes. GradeTripulantes only renders
 * from alocacoes, so we bridge them here.
 */
const EVENT_TYPE_TO_SITUACAO: Record<
  string,
  { situacao_tipo: NonNullable<EscalaAlocacao['situacao_tipo']>; cor: string; label: string }
> = {
  treinamento_simulador: { situacao_tipo: 'SIM', cor: '#9333EA', label: 'Simulador' },
  ferias: { situacao_tipo: 'FERIAS', cor: '#16A34A', label: 'Férias' },
  licenca: { situacao_tipo: 'AFT', cor: '#DC2626', label: 'Licença' },
  medico: { situacao_tipo: 'MED', cor: '#F59E0B', label: 'Médico' },
  treinamento_solo: { situacao_tipo: 'CURSO', cor: '#6366F1', label: 'Treinamento' },
};

/** Set of known tipo_evento values that can appear in synthetic IDs */
const KNOWN_TIPO_EVENTOS = new Set(Object.keys(EVENT_TYPE_TO_SITUACAO));

/** Synthetic ID prefix to distinguish bridge-generated alocacoes from real ones */
export const SYNTHETIC_ID_PREFIX = 'synthetic-';

/**
 * Returns true if the alocacao was generated by the bridge (from escala_eventos),
 * not persisted in escala_alocacoes.
 */
export function isSyntheticAlocacao(alocacao: Pick<EscalaAlocacao, 'id'>): boolean {
  return typeof alocacao.id === 'string' && alocacao.id.startsWith(SYNTHETIC_ID_PREFIX);
}

/**
 * Extract the original event ID and type from a synthetic alocacao ID.
 * Pattern: `synthetic-{tipo_evento}-{evento.id}`
 * Uses the known tipo_evento keys to correctly split even when evento.id contains hyphens.
 */
export function parseSyntheticId(id: string): { tipoEvento: string; eventoId: string } | null {
  if (!id.startsWith(SYNTHETIC_ID_PREFIX)) return null;
  const remainder = id.slice(SYNTHETIC_ID_PREFIX.length);

  // Try each known tipo_evento as a prefix (longest first to match correctly)
  const sortedTipos = [...KNOWN_TIPO_EVENTOS].sort((a, b) => b.length - a.length);
  for (const tipo of sortedTipos) {
    if (remainder.startsWith(tipo + '-')) {
      const eventoId = remainder.slice(tipo.length + 1);
      return { tipoEvento: tipo, eventoId };
    }
  }

  // Fallback: unknown tipo, split on first hyphen
  const firstDash = remainder.indexOf('-');
  if (firstDash === -1) return null;
  return {
    tipoEvento: remainder.slice(0, firstDash),
    eventoId: remainder.slice(firstDash + 1),
  };
}

/**
 * Build synthetic EscalaAlocacao objects from events in escala_eventos that
 * were synced from external modules (simuladores, funcionarios) but never
 * materialized in escala_alocacoes.
 *
 * The GradeTripulantes grid only renders from alocacoes — without this bridge,
 * externally-managed events would be invisible to tripulantes in the
 * traditional Escala Mensal view.
 *
 * ⚠️ Synthetic alocacoes are READ-ONLY. They must not be edited, deleted,
 *    published, or counted as real designations. Use isSyntheticAlocacao()
 *    to guard all mutation paths.
 */
export function buildSyntheticAlocacoesFromEventos(params: {
  eventos: EscalaEvento[];
  escalaId: string;
  tripulanteIds: Set<string>;
}): EscalaAlocacao[] {
  const { eventos, escalaId, tripulanteIds } = params;

  return eventos
    .filter(
      (evento) =>
        evento.escala_id === String(escalaId) &&
        tripulanteIds.has(evento.funcionario_id) &&
        evento.status !== 'cancelado' &&
        EVENT_TYPE_TO_SITUACAO[evento.tipo_evento] !== undefined,
    )
    .map((evento) => {
      const mapping = EVENT_TYPE_TO_SITUACAO[evento.tipo_evento];
      const now = new Date().toISOString();
      const syntheticId = `${SYNTHETIC_ID_PREFIX}${evento.tipo_evento}-${evento.id}`;

      // Preserve source traceability: store origem + original ID for navigation
      const sourceId = evento.id; // original escala_eventos.id (UUID)
      const sourceRoute = evento.origem || evento.tipo_evento;

      return {
        id: syntheticId,
        escala_id: escalaId,
        funcao: null as EscalaAlocacao['funcao'],
        situacao_tipo: mapping.situacao_tipo,
        situacao_cor: mapping.cor,
        situacao_nome: evento.observacoes || mapping.label,
        situacao_icone: null,
        situacao_bloqueia_alocacao: null,
        quinzena_id: null,
        data_inicio: evento.data_inicio,
        data_fim: evento.data_fim,
        padrao_escala_id: null,
        base: null,
        // Embed source traceability in observacoes for debugging (non-breaking)
        observacoes: evento.observacoes
          ? `${evento.observacoes} [fonte: ${sourceRoute}#${sourceId}]`
          : `[fonte: ${sourceRoute}#${sourceId}]`,
        status: (evento.status === 'confirmado'
          ? 'confirmado'
          : 'planejado') as EscalaAlocacao['status'],
        auto_gerado: true,
        created_by: null,
        created_at: now,
        updated_at: now,
        funcionario: {
          id: evento.funcionario_id,
          nome: evento.funcionario_nome || null,
          nome_guerra: null,
          matricula: evento.funcionario_matricula || null,
          role: evento.funcionario_cargo || null,
        },
        aeronave: {
          id: null,
          prefixo: null,
          modelo: null,
        },
        funcionario_id: evento.funcionario_id,
        funcionario_nome: evento.funcionario_nome || null,
        funcionario_guerra: null,
        funcionario_matricula: evento.funcionario_matricula || null,
        funcionario_role: evento.funcionario_cargo || null,
        funcionario_quinzena: null,
        funcionario_is_instrutor: undefined,
        aeronave_id: null,
        aeronave_prefixo: null,
        aeronave_modelo: null,
        modelo_aeronave: null,
        funcionario_modelo_aeronave: null,
        // ⚠️ Source metadata stored as comments — not part of EscalaAlocacao type
        // sourceId and sourceRoute for traceability
      } satisfies EscalaAlocacao;
    });
}

// Keep legacy alias for backward compat with any direct imports
export const buildSimulatorSyntheticAlocacoes = buildSyntheticAlocacoesFromEventos;

export function buildTripulanteAlocacoesMap(params: {
  tripulantes: EscalaCoberturaTripulante[];
  alocacoes: EscalaAlocacao[];
  intervaloInicio: string;
  intervaloFim: string;
}): Map<string, EscalaAlocacao[]> {
  const { tripulantes, alocacoes, intervaloInicio, intervaloFim } = params;
  const ids = new Set(tripulantes.map((tripulante) => tripulante.id));
  const mapa = new Map<string, EscalaAlocacao[]>();

  if (!intervaloInicio || !intervaloFim) {
    return mapa;
  }

  for (const alocacao of alocacoes) {
    if (!alocacao.funcionario_id || !ids.has(alocacao.funcionario_id)) continue;
    if (!overlapsPeriodo(alocacao.data_inicio, alocacao.data_fim, intervaloInicio, intervaloFim)) {
      continue;
    }

    const existentes = mapa.get(alocacao.funcionario_id) || [];
    existentes.push(alocacao);
    mapa.set(alocacao.funcionario_id, existentes);
  }

  return mapa;
}
