name = "airtrust-frontend-staging"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "../dist/client"

[env.staging]
name = "airtrust-frontend-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "airtrust-frontend"
vars = { ENVIRONMENT = "production", APP_VERSION = "managed-by-deploy" }
