-- ============================================================
-- FRMS_HELICOPTER_OFFSHORE_BASELINE_V1 (self-contained)
--
-- NOT a numbered migration. NOT applied to any environment by this file's
-- presence. Generated by
-- scripts/frms-seeds/generate-frms-helicopter-offshore-baseline-v1.ts
-- directly from LIMITES_DEFAULT / LEGACY_FADIGA_BUSINESS_POLICY /
-- LEGACY_FORTNIGHT_POLICY (worker-airtrust/src/lib/frms/{types,fadiga-score,
-- fortnight-indicator}.ts) — do not hand-edit the values below; regenerate
-- instead if a value ever needs to change (never in this baseline; V1 is a
-- pure governance snapshot of the current model, not a model change).
--
-- Deliberately self-contained: this file does NOT read from
-- frms_configuracao_limites and does NOT copy from any other revision
-- (e.g. 'frms-legacy-global-v2'). A real staging inspection found that
-- table empty, which leaves 0464's own bootstrap revision incomplete
-- (missing all 63 LimitesMap parameters) — this baseline must not inherit
-- that gap regardless of what any other table or revision contains.
--
-- Governance only: no formula, weight, threshold, or alert logic is
-- changed. profile_code = 'HELICOPTER_OFFSHORE', policy_version (stored as
-- model_version per the existing schema convention) = 'LEGACY_MODEL_V2'.
--
-- empresa_id = NULL: this is a global default revision. No
-- frms_regulatory_profiles row and no frms_profile_assignments row are
-- created here — frms_regulatory_profiles.empresa_id is NOT NULL by schema
-- (0463), so a regulatory profile is inherently tenant-scoped and only
-- meaningful once a real tenant is being assigned to this profile_code.
-- That assignment (and its regulatory-profile row) is a separate, explicit,
-- tenant-scoped, reviewed action — not implied by seeding this baseline.
--
-- FAIL-CLOSED reapply: rerunning this file against a DB that already has
-- this revision will fail on the UNIQUE(revision_id, parameter_key)
-- constraint rather than silently duplicate or diverge. Use
-- scripts/frms-seeds/apply-frms-helicopter-offshore-baseline-v1.mjs for a
-- safe, idempotent-aware apply (checks existing content before writing).
-- ============================================================

INSERT INTO frms_config_revisions (
  id, empresa_id, profile_code, revision_number, status, source_type,
  source_reference, regulatory_profile_id, policy_version, effective_from, effective_to,
  actor_user_id, reason, supersedes_revision_id, created_at
) VALUES (
  'frms-helicopter-offshore-baseline-v1', NULL, 'HELICOPTER_OFFSHORE', 1, 'ACTIVE', 'INTERNAL_POLICY',
  'FRMS_HELICOPTER_OFFSHORE_BASELINE_V1 — governance migration only, self-contained, no formula/value change',
  NULL, 'LEGACY_MODEL_V2', '1970-01-01', NULL,
  NULL,
  'First governed revision for HELICOPTER_OFFSHORE: snapshots the current LIMITES_DEFAULT/LEGACY_FADIGA_BUSINESS_POLICY/LEGACY_FORTNIGHT_POLICY values verbatim (generated from source, not copied from any other revision or table) to make the offshore configuration auditable and versioned before any future model evolution.',
  NULL, datetime('now')
);

INSERT INTO frms_config_parameters (
  id, revision_id, parameter_key, numeric_value, json_value, unit, metric, window_kind, direction, required, created_at
) VALUES
  ('frms-helicopter-offshore-baseline-v1-ALERTA_ATENCAO_PCT', 'frms-helicopter-offshore-baseline-v1', 'ALERTA_ATENCAO_PCT', 90, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-ALERTA_AVISO_PCT', 'frms-helicopter-offshore-baseline-v1', 'ALERTA_AVISO_PCT', 80, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-ALERTA_CRITICO_PCT', 'frms-helicopter-offshore-baseline-v1', 'ALERTA_CRITICO_PCT', 95, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-ALERTA_VIOLACAO_PCT', 'frms-helicopter-offshore-baseline-v1', 'ALERTA_VIOLACAO_PCT', 101, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_AMANHECER_FATOR', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_AMANHECER_FATOR', -0.05, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_AMANHECER_H_MAX', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_AMANHECER_H_MAX', 6, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_AMANHECER_H_MIN', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_AMANHECER_H_MIN', 5, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_DIURNO_FATOR', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_DIURNO_FATOR', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_DIURNO_H_MAX', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_DIURNO_H_MAX', 11, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_DIURNO_H_MIN', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_DIURNO_H_MIN', 7, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_MADRUGADA_FATOR', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_MADRUGADA_FATOR', -0.2, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_MADRUGADA_H_MAX', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_MADRUGADA_H_MAX', 4, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_MADRUGADA_H_MIN', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_MADRUGADA_H_MIN', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_NOITE_FATOR', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_NOITE_FATOR', -0.2, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_TARDE_FATOR', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_TARDE_FATOR', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_TARDE_H_MAX', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_TARDE_H_MAX', 17, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-APRESENTACAO_TARDE_H_MIN', 'frms-helicopter-offshore-baseline-v1', 'APRESENTACAO_TARDE_H_MIN', 12, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-CICLO_EMBARCADO_ATIVO', 'frms-helicopter-offshore-baseline-v1', 'CICLO_EMBARCADO_ATIVO', 1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-CICLO_EMBARCADO_DIA_INICIO', 'frms-helicopter-offshore-baseline-v1', 'CICLO_EMBARCADO_DIA_INICIO', 1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-CICLO_EMBARCADO_DIA_MAX', 'frms-helicopter-offshore-baseline-v1', 'CICLO_EMBARCADO_DIA_MAX', 15, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-CICLO_EMBARCADO_PCT_MAX', 'frms-helicopter-offshore-baseline-v1', 'CICLO_EMBARCADO_PCT_MAX', -0.15, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-CICLO_EMBARCADO_PCT_MIN', 'frms-helicopter-offshore-baseline-v1', 'CICLO_EMBARCADO_PCT_MIN', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-DURACAO_CURTA_FATOR', 'frms-helicopter-offshore-baseline-v1', 'DURACAO_CURTA_FATOR', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-DURACAO_CURTA_MINUTOS', 'frms-helicopter-offshore-baseline-v1', 'DURACAO_CURTA_MINUTOS', 360, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-DURACAO_LONGA_FATOR', 'frms-helicopter-offshore-baseline-v1', 'DURACAO_LONGA_FATOR', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-DURACAO_LONGA_MINUTOS', 'frms-helicopter-offshore-baseline-v1', 'DURACAO_LONGA_MINUTOS', 600, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-DURACAO_NORMAL_FATOR', 'frms-helicopter-offshore-baseline-v1', 'DURACAO_NORMAL_FATOR', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-EFFECTIV_AMARELO_MAX', 'frms-helicopter-offshore-baseline-v1', 'EFFECTIV_AMARELO_MAX', 77, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-EFFECTIV_PERIODO_PCT', 'frms-helicopter-offshore-baseline-v1', 'EFFECTIV_PERIODO_PCT', 30, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-EFFECTIV_VERDE_MIN', 'frms-helicopter-offshore-baseline-v1', 'EFFECTIV_VERDE_MIN', 90, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-EFFECTIV_VERMELHO_MAX', 'frms-helicopter-offshore-baseline-v1', 'EFFECTIV_VERMELHO_MAX', 65, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FATIGUE_ALCOHOL_BONUS', 'frms-helicopter-offshore-baseline-v1', 'FATIGUE_ALCOHOL_BONUS', 15, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FATIGUE_MEDICATION_BONUS', 'frms-helicopter-offshore-baseline-v1', 'FATIGUE_MEDICATION_BONUS', 8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FATOR_ACLIMATADO_NAO_PCT', 'frms-helicopter-offshore-baseline-v1', 'FATOR_ACLIMATADO_NAO_PCT', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FATOR_BASE_AWAY_PCT', 'frms-helicopter-offshore-baseline-v1', 'FATOR_BASE_AWAY_PCT', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FATOR_TRIPULACAO_AUM_HORAS', 'frms-helicopter-offshore-baseline-v1', 'FATOR_TRIPULACAO_AUM_HORAS', 2, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FDP_ALERTA_RESTANTE_HORAS', 'frms-helicopter-offshore-baseline-v1', 'FDP_ALERTA_RESTANTE_HORAS', 3, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FDP_MAXIMO_HORAS', 'frms-helicopter-offshore-baseline-v1', 'FDP_MAXIMO_HORAS', 11, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_CONSECUTIVE_DAYS_ATTENTION', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_CONSECUTIVE_DAYS_ATTENTION', 4, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_CONSECUTIVE_DAYS_CRITICAL', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_CONSECUTIVE_DAYS_CRITICAL', 5, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_DAYS_WITHOUT_DUTY', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_DAYS_WITHOUT_DUTY', 2, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_EARLY_0600_MINUTES', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_EARLY_0600_MINUTES', 360, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_EARLY_0700_MINUTES', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_EARLY_0700_MINUTES', 420, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_CHECKIN_PENDING', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_CHECKIN_PENDING', 10, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_COMPLETE_DATA', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_COMPLETE_DATA', -4, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_CONSECUTIVE_ATTENTION', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_CONSECUTIVE_ATTENTION', 8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_CONSECUTIVE_CRITICAL', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_CONSECUTIVE_CRITICAL', 14, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_DAILY_ATTENTION', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_DAILY_ATTENTION', 7, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_DAILY_CRITICAL', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_DAILY_CRITICAL', 18, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_DAYS_WITHOUT_DUTY', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_DAYS_WITHOUT_DUTY', -8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_EARLY_0600', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_EARLY_0600', 8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_ESTIMATED_DATA', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_ESTIMATED_DATA', 7, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_HIGH_KSS', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_HIGH_KSS', 12, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_LONG_REST', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_LONG_REST', -6, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_LOW_EFFECTIVENESS', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_LOW_EFFECTIVENESS', 14, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_LOW_SLEEP', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_LOW_SLEEP', 12, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_NO_EARLY_PRESENTATION', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_NO_EARLY_PRESENTATION', -3, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_RECURRING_EARLY', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_RECURRING_EARLY', 5, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_ROLLING_DUTY', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_ROLLING_DUTY', 10, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_SHORT_AVG_DUTY', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_SHORT_AVG_DUTY', -5, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_IMPACT_SHORT_REST', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_IMPACT_SHORT_REST', 16, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_LONG_REST_MINUTES', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_LONG_REST_MINUTES', 780, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_LOW_EFFECTIVENESS_PCT', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_LOW_EFFECTIVENESS_PCT', 70, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_LOW_SLEEP_HOURS', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_LOW_SLEEP_HOURS', 6, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_RECURRING_EARLY_PRESENTATIONS', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_RECURRING_EARLY_PRESENTATIONS', 2, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_ROLLING_DUTY_PCT', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_ROLLING_DUTY_PCT', 0.8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_SCORE_ATTENTION', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_SCORE_ATTENTION', 45, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_SCORE_CRITICAL', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_SCORE_CRITICAL', 75, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_SCORE_LIMIT_WEIGHT', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_SCORE_LIMIT_WEIGHT', 0.65, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_SHORT_AVG_DUTY_MINUTES', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_SHORT_AVG_DUTY_MINUTES', 360, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_SHORT_REST_MINUTES', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_SHORT_REST_MINUTES', 600, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_TREND_INCREASING_IMPACT', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_TREND_INCREASING_IMPACT', 6, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FORTNIGHT_TREND_REDUCING_IMPACT', 'frms-helicopter-offshore-baseline-v1', 'FORTNIGHT_TREND_REDUCING_IMPACT', -4, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-FRMS_EMBARQUE_PROGRESSO_MAX', 'frms-helicopter-offshore-baseline-v1', 'FRMS_EMBARQUE_PROGRESSO_MAX', 8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HORAS_SONO_PADRAO', 'frms-helicopter-offshore-baseline-v1', 'HORAS_SONO_PADRAO', 8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_28_DIAS_HORAS', 'frms-helicopter-offshore-baseline-v1', 'HV_28_DIAS_HORAS', 93, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_365_DIAS_HORAS', 'frms-helicopter-offshore-baseline-v1', 'HV_365_DIAS_HORAS', 930, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_7_DIAS_HORAS', 'frms-helicopter-offshore-baseline-v1', 'HV_7_DIAS_HORAS', 45, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_DIARIA_HORAS', 'frms-helicopter-offshore-baseline-v1', 'HV_DIARIA_HORAS', 8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_DIA_ALERTA_RESTANTE_HORAS', 'frms-helicopter-offshore-baseline-v1', 'HV_DIA_ALERTA_RESTANTE_HORAS', 2, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_MES_HORAS', 'frms-helicopter-offshore-baseline-v1', 'HV_MES_HORAS', 90, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_MUITAS_FATOR', 'frms-helicopter-offshore-baseline-v1', 'HV_MUITAS_FATOR', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_MUITAS_MINUTOS', 'frms-helicopter-offshore-baseline-v1', 'HV_MUITAS_MINUTOS', 300, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_NORMAL_FATOR', 'frms-helicopter-offshore-baseline-v1', 'HV_NORMAL_FATOR', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_POUCAS_FATOR', 'frms-helicopter-offshore-baseline-v1', 'HV_POUCAS_FATOR', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-HV_POUCAS_MINUTOS', 'frms-helicopter-offshore-baseline-v1', 'HV_POUCAS_MINUTOS', 120, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-KSS_HIGH_THRESHOLD', 'frms-helicopter-offshore-baseline-v1', 'KSS_HIGH_THRESHOLD', 7, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-KSS_NORM_EQ_7', 'frms-helicopter-offshore-baseline-v1', 'KSS_NORM_EQ_7', 0.7, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-KSS_NORM_EQ_8', 'frms-helicopter-offshore-baseline-v1', 'KSS_NORM_EQ_8', 0.85, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-KSS_NORM_GE_9', 'frms-helicopter-offshore-baseline-v1', 'KSS_NORM_GE_9', 1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-KSS_NORM_LE_2', 'frms-helicopter-offshore-baseline-v1', 'KSS_NORM_LE_2', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-KSS_NORM_LE_4', 'frms-helicopter-offshore-baseline-v1', 'KSS_NORM_LE_4', 0.15, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-KSS_NORM_LE_6', 'frms-helicopter-offshore-baseline-v1', 'KSS_NORM_LE_6', 0.4, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-MINUTOS_ANTES_APRESENTACAO', 'frms-helicopter-offshore-baseline-v1', 'MINUTOS_ANTES_APRESENTACAO', 90, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-NOTURNO_FATOR', 'frms-helicopter-offshore-baseline-v1', 'NOTURNO_FATOR', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-NOTURNO_FIM_HORA', 'frms-helicopter-offshore-baseline-v1', 'NOTURNO_FIM_HORA', 5, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-NOTURNO_INICIO_HORA', 'frms-helicopter-offshore-baseline-v1', 'NOTURNO_INICIO_HORA', 22, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_ADEQUADO_FATOR', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_ADEQUADO_FATOR', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_ADEQUADO_MINUTOS', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_ADEQUADO_MINUTOS', 720, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_CRITICO_FATOR', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_CRITICO_FATOR', -0.2, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_MINIMO_HORAS', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_MINIMO_HORAS', 12, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_MIN_POS_LIBERACAO', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_MIN_POS_LIBERACAO', 60, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_MIN_PRE_APRESENTACAO', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_MIN_PRE_APRESENTACAO', 90, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_PLATAFORMA_MAXIMO_HORAS', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_PLATAFORMA_MAXIMO_HORAS', 6, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_PLATAFORMA_MINIMO_HORAS', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_PLATAFORMA_MINIMO_HORAS', 3, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_QUALIDADE_HOTEL', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_QUALIDADE_HOTEL', 92, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_RUIM_FATOR', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_RUIM_FATOR', -0.1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-REPOUSO_RUIM_MINUTOS', 'frms-helicopter-offshore-baseline-v1', 'REPOUSO_RUIM_MINUTOS', 480, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_DURATION_GE_4_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_DURATION_GE_4_NORM', 0.8, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_DURATION_GE_5_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_DURATION_GE_5_NORM', 0.6, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_DURATION_GE_6_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_DURATION_GE_6_NORM', 0.35, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_DURATION_GE_7_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_DURATION_GE_7_NORM', 0.15, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_DURATION_GE_8_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_DURATION_GE_8_NORM', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_DURATION_LT_4_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_DURATION_LT_4_NORM', 1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_DURATION_MISSING_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_DURATION_MISSING_NORM', 0.6, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_QUALITY_EQ_2_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_QUALITY_EQ_2_NORM', 0.7, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_QUALITY_EQ_3_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_QUALITY_EQ_3_NORM', 0.45, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_QUALITY_EQ_4_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_QUALITY_EQ_4_NORM', 0.2, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_QUALITY_GE_5_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_QUALITY_GE_5_NORM', 0, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_QUALITY_LT_2_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_QUALITY_LT_2_NORM', 1, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-SLEEP_QUALITY_MISSING_NORM', 'frms-helicopter-offshore-baseline-v1', 'SLEEP_QUALITY_MISSING_NORM', 0.4, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-VISUAL_ATENCAO_PCT', 'frms-helicopter-offshore-baseline-v1', 'VISUAL_ATENCAO_PCT', 85, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-VISUAL_AVISO_PCT', 'frms-helicopter-offshore-baseline-v1', 'VISUAL_AVISO_PCT', 40, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-VISUAL_CRITICO_PCT', 'frms-helicopter-offshore-baseline-v1', 'VISUAL_CRITICO_PCT', 95, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-WOCL_CENTER_PENALTY', 'frms-helicopter-offshore-baseline-v1', 'WOCL_CENTER_PENALTY', 0.3, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-WOCL_EDGE_PENALTY', 'frms-helicopter-offshore-baseline-v1', 'WOCL_EDGE_PENALTY', 0.15, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-WOCL_END_MINUTE', 'frms-helicopter-offshore-baseline-v1', 'WOCL_END_MINUTE', 360, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now')),
  ('frms-helicopter-offshore-baseline-v1-WOCL_START_MINUTE', 'frms-helicopter-offshore-baseline-v1', 'WOCL_START_MINUTE', 120, NULL, 'unit', NULL, NULL, NULL, 1, datetime('now'));
